// DAD Budget 2027 - shared frontend logic
(function(){
  const BASE='dadBudgetIMSSales', META=BASE+'Meta', PREFIX=BASE+'Chunk_', CHUNK_SIZE=250;
  const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  const n=v=>{const x=Number(String(v??'').replace(/,/g,'').replace('%','').trim());return Number.isFinite(x)?x:0};
  const money=v=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2});
  const qty=v=>Math.round(Number(v||0)).toLocaleString();
  const norm=v=>String(v??'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'');

  function setupShell(){
    const lf=document.getElementById('loginForm');if(lf)lf.addEventListener('submit',e=>{e.preventDefault();location.href='index.html'});
    const lo=document.getElementById('logoutBtn');if(lo)lo.addEventListener('click',()=>location.href='login.html');
    const shell=document.querySelector('.app-shell'),side=document.querySelector('.sidebar');if(!shell||!side)return;
    const nav=side.querySelector('.sidebar-nav');if(nav&&!nav.querySelector('a[href="data-admin.html"]')){const s=document.createElement('div');s.className='nav-section';s.textContent='ADMIN';const a=document.createElement('a');a.href='data-admin.html';a.textContent='Data Admin';nav.append(s,a)}
    let b=side.querySelector('.sidebar-toggle');if(!b){b=document.createElement('button');b.type='button';b.className='sidebar-toggle';b.title='Open / Close Sidebar';b.textContent='‹';side.appendChild(b)}
    if(localStorage.getItem('dadBudgetSidebarCollapsed')==='true')shell.classList.add('sidebar-collapsed');
    b.addEventListener('click',()=>{shell.classList.toggle('sidebar-collapsed');localStorage.setItem('dadBudgetSidebarCollapsed',shell.classList.contains('sidebar-collapsed')?'true':'false')});
  }

  function clearIMS(){let meta=null;try{meta=JSON.parse(localStorage.getItem(META)||'null')}catch(e){};for(let i=0;i<n(meta?.chunkCount);i++)localStorage.removeItem(PREFIX+i);localStorage.removeItem(META);localStorage.removeItem(BASE);localStorage.removeItem('dadBudgetIMSSalesData')}
  function saveIMS(payload){clearIMS();const rows=payload.rows||[],count=Math.ceil(rows.length/CHUNK_SIZE);for(let i=0;i<count;i++)localStorage.setItem(PREFIX+i,JSON.stringify(rows.slice(i*CHUNK_SIZE,(i+1)*CHUNK_SIZE)));const meta={...payload,rows:undefined,chunked:true,chunkSize:CHUNK_SIZE,chunkCount:count,rowCount:rows.length};delete meta.rows;localStorage.setItem(META,JSON.stringify(meta));localStorage.setItem(BASE,JSON.stringify({chunked:true,chunkSize:CHUNK_SIZE,chunkCount:count,rowCount:rows.length}));return meta}
  function loadMeta(){try{return JSON.parse(localStorage.getItem(META)||'null')}catch(e){return null}}
  function loadAllRows(){const m=loadMeta();if(!m)return[];const out=[];for(let i=0;i<n(m.chunkCount);i++){try{const a=JSON.parse(localStorage.getItem(PREFIX+i)||'[]');if(Array.isArray(a))out.push(...a)}catch(e){}}return out}

  function findHeaderRow(matrix){for(let i=0;i<Math.min(matrix.length,15);i++){const h=(matrix[i]||[]).map(v=>String(v??'').trim().toLowerCase().replace(/\s+/g,' '));if(h.includes('region')&&h.includes('country')&&h.includes('agent')&&h.includes('sku')&&h.includes('total qty'))return i}return-1}
  function hidx(h,names){const c=h.map(v=>String(v??'').trim().toLowerCase().replace(/\s+/g,' '));for(const x of names){const i=c.indexOf(x.toLowerCase());if(i>=0)return i}return-1}
  function bonus(v){const x=n(v);return Math.abs(x)<=1?x*100:x}
  async function parseIMS(file){if(typeof XLSX==='undefined')throw new Error('Excel reader is not loaded');const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array'}),sn=wb.SheetNames.find(x=>String(x).trim().toUpperCase()==='B26')||wb.SheetNames[0],mx=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:'',raw:true}),hi=findHeaderRow(mx);if(hi<0)throw new Error('B26 sales headers were not found');const h=mx[hi],ix={region:hidx(h,['Region']),type:hidx(h,['Type']),country:hidx(h,['Country']),subMarket:hidx(h,['Sub Market']),agent:hidx(h,['Agent']),sector:hidx(h,['Sector']),brand:hidx(h,['Brand']),sku:hidx(h,['SKU']),category:hidx(h,['Product Category']),price:hidx(h,['Price USD']),totalQty:hidx(h,['Total QTY']),bonus:hidx(h,['B26 Bonus %','Bonus %'])};const mi=MONTHS.map(m=>hidx(h,[m]));if([ix.region,ix.country,ix.agent,ix.sku,ix.price,ix.totalQty,...mi].some(i=>i<0))throw new Error('Required IMS columns are missing');const rows=[];let tq=0,ts=0,mm=0;for(let r=hi+1;r<mx.length;r++){const x=mx[r]||[],sku=String(x[ix.sku]??'').trim(),country=String(x[ix.country]??'').trim(),agent=String(x[ix.agent]??'').trim();if(!sku&&!country&&!agent)continue;const months=mi.map(i=>n(x[i])),calc=months.reduce((a,b)=>a+b,0),src=n(x[ix.totalQty]);if(Math.abs(calc-src)>.0001)mm++;const price=n(x[ix.price]),use=src||calc,sales=months.map(q=>q*price),row={region:String(x[ix.region]??'').trim(),type:ix.type>=0?String(x[ix.type]??'').trim():'',country,subMarket:ix.subMarket>=0?String(x[ix.subMarket]??'').trim():'',agent,sector:ix.sector>=0?String(x[ix.sector]??'').trim():'',brand:ix.brand>=0?String(x[ix.brand]??'').trim():'',sku,category:ix.category>=0?String(x[ix.category]??'').trim():'',price,months,totalQty:use,sourceTotalQty:src,bonusPct:ix.bonus>=0?bonus(x[ix.bonus]):0,sales,totalSales:use*price};rows.push(row);tq+=use;ts+=row.totalSales}if(!rows.length)throw new Error('No IMS sales rows were found');return{version:2,fileName:file.name,uploadedAt:new Date().toISOString(),sheetName:sn,rows,validation:{rows:rows.length,totalQty:tq,totalSales:ts,totalQtyMismatches:mm}}}

  function setupAdminUpload(){const input=document.getElementById('imsInput');if(!input)return;input.addEventListener('change',async e=>{e.stopImmediatePropagation();const file=e.target.files?.[0];if(!file)return;const st=document.getElementById('imsStatus'),fe=document.getElementById('imsFile');try{if(st){st.textContent='Reading...';st.classList.remove('ready','error')}const payload=await parseIMS(file),meta=saveIMS(payload);localStorage.setItem('dadBudgetIMSFileName',file.name);localStorage.setItem('dadBudgetAdmin_ims',JSON.stringify({name:file.name,updated:payload.uploadedAt,rows:payload.validation.rows,mismatches:payload.validation.totalQtyMismatches,chunks:meta.chunkCount,statusText:`${payload.validation.rows} rows • ${meta.chunkCount} chunks`}));if(fe)fe.textContent=file.name;if(st){st.textContent=`${payload.validation.rows} rows • ${meta.chunkCount} chunks`;st.classList.add('ready')}alert(`IMS Sales loaded successfully\n\nRows: ${payload.validation.rows.toLocaleString()}\nChunks: ${meta.chunkCount}\nTotal QTY: ${qty(payload.validation.totalQty)}\nTotal Sales USD: ${money(payload.validation.totalSales)}\nQTY check issues: ${payload.validation.totalQtyMismatches}`)}catch(err){if(st){st.textContent='Upload error';st.classList.add('error')}alert('IMS upload error: '+err.message)}finally{input.value=''}},true);const m=loadMeta();if(m){const st=document.getElementById('imsStatus'),fe=document.getElementById('imsFile');if(fe)fe.textContent=m.fileName||'Loaded file';if(st){st.textContent=`${n(m.rowCount)} rows • ${n(m.chunkCount)} chunks`;st.classList.add('ready')}}}

  function setupIMS(){const table=document.getElementById('budgetTable');if(!table)return;const tbody=table.tBodies[0],wrap=document.querySelector('.table-wrap'),meta=loadMeta(),all=loadAllRows(),costMap=(()=>{try{return JSON.parse(localStorage.getItem('dadBudgetCostMaster')||'{}')||{}}catch(e){return{}}})();let filtered=all,page=0;const PAGE=250;
    const style=document.createElement('style');style.textContent=`.budget-table tbody tr:not(.total-row):hover td{font-weight:900!important;color:#063f3d!important;background:#e6fffb!important;text-shadow:0 0 7px rgba(20,225,205,.72);box-shadow:inset 0 0 14px rgba(28,222,202,.22)}.reduction-group{background:#8b5a43!important}.reduction-head{background:#744936!important;color:#fff!important}.reduction-pct,.reduction-usd{font-weight:900!important}.net-sales-group,.net-sales-head{background:#1f6673!important;color:#fff!important}.gp-group,.gp-head,.gp-pct-head{background:#176d63!important;color:#fff!important}.fte-group,.fte-head{background:#31566e!important;color:#fff!important}.direct-cost-group,.direct-cost-head{background:#514d70!important;color:#fff!important}.fte-sep,.reduction-sep,.direct-cost-sep,.fte-sep-head,.reduction-sep-head,.direct-cost-sep-head{min-width:18px!important;width:18px!important;max-width:18px!important;padding:0!important;background:#eef2f2!important}.ims-chunk-nav{display:flex;align-items:center;gap:7px}.ims-chunk-nav button{border:1px solid #b9dcd8;background:#fff;color:#0b6661;border-radius:8px;padding:6px 9px;font-size:10px;font-weight:900}.ims-chunk-nav button:disabled{opacity:.4;cursor:default}.ims-chunk-nav span{font-size:10px;color:#60777c;font-weight:800}`;document.head.appendChild(style);
    const group=table.querySelector('thead .group-row'),head=table.querySelector('thead .column-row'),costGroup=table.querySelector('.cost-group');
    if(!head.querySelector('.bonus-head')){const g=document.createElement('th');g.className='bonus-group';g.colSpan=2;g.textContent='BONUS 2026';group.insertBefore(g,costGroup);const h1=document.createElement('th'),h2=document.createElement('th');h1.className='bonus-head';h1.textContent='Bonus %';h2.className='bonus-head';h2.textContent='Bonus QTY';head.children[35].after(h1,h2)}
    if(!head.querySelector('.reduction-head')){const g=document.createElement('th');g.className='reduction-group';g.colSpan=8;g.textContent='REDUCTIONS';group.insertBefore(g,costGroup);let a=[...head.children].find(x=>x.textContent.trim()==='Bonus QTY');[['Commission %','commission-pct'],['Commission USD','commission-usd'],['','reduction-sep'],['Returns %','returns-pct'],['Returns USD','returns-usd'],['','reduction-sep'],['Discount %','discount-pct'],['Discount USD','discount-usd']].forEach(([t,c])=>{const th=document.createElement('th');th.className='reduction-head '+(c.includes('sep')?'reduction-sep-head ':'')+c;th.textContent=t;a.after(th);a=th})}
    if(!head.querySelector('.net-sales-head')){const g=document.createElement('th');g.className='net-sales-group';g.colSpan=1;g.textContent='NET SALES';group.insertBefore(g,costGroup);const h=document.createElement('th');h.className='net-sales-head';h.textContent='Net Sales';[...head.children].find(x=>x.textContent.trim()==='Discount USD').after(h)}
    if(!head.querySelector('.gp-head')){const g=document.createElement('th');g.className='gp-group';g.colSpan=2;g.textContent='PROFITABILITY';group.appendChild(g);const a=document.createElement('th'),b=document.createElement('th');a.className='gp-head';a.textContent='Gross Profit';b.className='gp-pct-head';b.textContent='GP%';head.append(a,b)}
    if(!head.querySelector('.fte-head')){const g=document.createElement('th');g.className='fte-group';g.colSpan=7;g.textContent='FTE / PRODUCT';group.appendChild(g);let a=head.querySelector('.gp-pct-head');[['FTE %<br>MR','fte-mr-pct'],['FTE USD<br>MR','fte-mr-usd'],['','fte-sep'],['FTE %<br>MGR, SUPR','fte-mgr-pct'],['FTE USD<br>MGR, SUPR','fte-mgr-usd'],['','fte-sep'],['Total FTE','fte-total-head']].forEach(([t,c])=>{const th=document.createElement('th');th.className='fte-head '+(c.includes('sep')?'fte-sep-head ':'')+c;th.innerHTML=t;a.after(th);a=th})}
    if(!head.querySelector('.direct-cost-head')){const g=document.createElement('th');g.className='direct-cost-group';g.colSpan=7;g.textContent='DIRECT COSTS / PROFIT';group.appendChild(g);let a=head.querySelector('.fte-total-head');[['B26<br>Samples QTY','samples-qty-head'],['B26<br>Samples USD','samples-usd-head'],['','direct-cost-sep-head'],['A&P<br>USD $','ap-head'],['','direct-cost-sep-head'],['Profit after direct costs','profit-direct-head'],['Net Profit %','net-profit-pct-head']].forEach(([t,c])=>{const th=document.createElement('th');th.className='direct-cost-head '+c;th.innerHTML=t;a.after(th);a=th})}
    const td=(t,c='')=>{const x=document.createElement('td');x.textContent=t;x.className=c;return x};
    function calcTotals(data){const qm=Array(12).fill(0),sm=Array(12).fill(0);let tq=0,ts=0,bq=0;data.forEach(r=>{r.months.forEach((v,i)=>qm[i]+=n(v));r.sales.forEach((v,i)=>sm[i]+=n(v));tq+=n(r.totalQty);ts+=n(r.totalSales);bq+=n(r.totalQty)*n(r.bonusPct)/100});return{qm,sm,tq,ts,bq}}
    function rowEl(r){const tr=document.createElement('tr');tr.dataset.sku=r.sku||'';const base=[r.region,r.type,r.country,r.subMarket,r.agent,r.sector,r.brand,r.sku,r.category];base.forEach((v,i)=>tr.appendChild(td(v||'',`text sticky-${i+1}`)));tr.appendChild(td(money(r.price),'price-col sticky-10'));r.months.forEach(v=>tr.appendChild(td(qty(v),'qty-cell')));tr.appendChild(td(qty(r.totalQty),'total-cell'));r.sales.forEach(v=>tr.appendChild(td(money(v),'sales-cell')));tr.appendChild(td(money(r.totalSales),'total-cell'));const bp=n(r.bonusPct),bq=n(r.totalQty)*bp/100;tr.append(td(bp.toFixed(2)+'%','bonus-percent'),td(qty(bq),'bonus-qty'));['commission','returns','discount'].forEach((k,i)=>{const p=td('0.00%',`reduction-pct ${k}-pct`),u=td('0',`reduction-usd ${k}-usd`);p.contentEditable='true';p.dataset.raw='0';tr.append(p,u);if(i<2)tr.appendChild(td('','reduction-sep'))});tr.appendChild(td(money(r.totalSales),'net-sales-cell'));const cost=n(costMap[norm(r.sku)]);tr.appendChild(td(cost?money(cost):'—','cost-unit'+(cost?'':' unmatched-cost')));for(let i=0;i<12;i++)tr.appendChild(td(cost?money(n(r.months[i])*cost):'—','cogs-cell'));const cogs=(n(r.totalQty)+bq)*cost;tr.appendChild(td(cost?money(cogs):'—','cogs-total'));const gp=n(r.totalSales)-(cost?cogs:0);tr.append(td(money(gp),'gp-cell'+(gp<0?' negative':'')),td(r.totalSales?(gp/r.totalSales*100).toFixed(2)+'%':'—','gp-pct-cell'));[['0.00%','fte-pct fte-mr-pct-cell'],['0','fte-usd fte-mr-usd-cell'],['','fte-sep'],['0.00%','fte-pct fte-mgr-pct-cell'],['0','fte-usd fte-mgr-usd-cell'],['','fte-sep'],['0','fte-total-cell'],['0','samples-qty-cell'],['0','samples-usd-cell'],['','direct-cost-sep'],['0','ap-cell'],['','direct-cost-sep'],[money(gp),'profit-direct-cell'],[r.totalSales?(gp/r.totalSales*100).toFixed(2)+'%':'—','net-profit-pct-cell']].forEach(([t,c])=>tr.appendChild(td(t,c)));return tr}
    function render(){const pages=Math.max(1,Math.ceil(filtered.length/PAGE));if(page>=pages)page=pages-1;const slice=filtered.slice(page*PAGE,(page+1)*PAGE),frag=document.createDocumentFragment();slice.forEach(r=>frag.appendChild(rowEl(r)));const T=calcTotals(filtered),tr=document.createElement('tr');tr.className='total-row';tr.appendChild(td('TOTAL','text sticky-1'));for(let i=2;i<=10;i++)tr.appendChild(td('',`sticky-${i}`));T.qm.forEach(v=>tr.appendChild(td(qty(v))));tr.appendChild(td(qty(T.tq)));T.sm.forEach(v=>tr.appendChild(td(money(v))));tr.appendChild(td(money(T.ts)));tr.append(td('—','bonus-total'),td(qty(T.bq),'bonus-total'));for(let i=0;i<8;i++)tr.appendChild(td(i%3===2?'':'0',i%3===2?'reduction-sep':'reduction-total'));tr.appendChild(td(money(T.ts),'net-sales-total'));for(let i=0;i<14;i++)tr.appendChild(td(i===0?'—':'','cost-total-row'));tr.append(td('','gp-total'),td('','gp-pct-total'));for(let i=0;i<14;i++)tr.appendChild(td('',i===2||i===5?'fte-sep':i===9||i===11?'direct-cost-sep':'fte-total-row'));tbody.replaceChildren(frag,tr);document.getElementById('imsEmpty').style.display=filtered.length?'none':'block';document.getElementById('imsRowBadge').textContent=`${filtered.length.toLocaleString()} Rows`;document.getElementById('imsSourceLine').textContent=meta?`${meta.fileName||'IMS Sales'} • ${filtered.length.toLocaleString()} rows • showing ${slice.length} rows`:'No IMS Sales file loaded yet.';navInfo.textContent=`Chunk ${page+1} / ${pages}`;prev.disabled=page<=0;next.disabled=page>=pages-1;if(wrap)wrap.scrollTop=0}
    const badge=document.querySelector('.sheet-badges'),nav=document.createElement('div'),prev=document.createElement('button'),next=document.createElement('button'),navInfo=document.createElement('span');nav.className='ims-chunk-nav';prev.textContent='‹ Prev';next.textContent='Next ›';nav.append(prev,navInfo,next);badge?.prepend(nav);prev.addEventListener('click',()=>{if(page>0){page--;render()}});next.addEventListener('click',()=>{if((page+1)*PAGE<filtered.length){page++;render()}});
    const ids=[['filterRegion','region'],['filterCountry','country'],['filterAgent','agent'],['filterSector','sector']];ids.forEach(([id,key])=>{const el=document.getElementById(id);[...new Set(all.map(r=>r[key]).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b))).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)})});function apply(){const rv=document.getElementById('filterRegion').value,cv=document.getElementById('filterCountry').value,av=document.getElementById('filterAgent').value,sv=document.getElementById('filterSector').value,qv=document.getElementById('filterSearch').value.trim().toLowerCase();filtered=all.filter(r=>(!rv||r.region===rv)&&(!cv||r.country===cv)&&(!av||r.agent===av)&&(!sv||r.sector===sv)&&(!qv||String(r.brand).toLowerCase().includes(qv)||String(r.sku).toLowerCase().includes(qv)));page=0;render()}ids.forEach(([id])=>document.getElementById(id).addEventListener('change',apply));document.getElementById('filterSearch').addEventListener('input',apply);document.getElementById('clearFilters').addEventListener('click',()=>{ids.forEach(([id])=>document.getElementById(id).value='');document.getElementById('filterSearch').value='';filtered=all;page=0;render()});render();
  }
  document.addEventListener('DOMContentLoaded',()=>{setupShell();setupAdminUpload();setupIMS()});
})();