(function(){
'use strict';
const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const $=id=>document.getElementById(id);
const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toUpperCase().replace(/[^A-Z0-9]/g,'');
const num=v=>{let s=clean(v).replace(/,/g,'');if(/^\(.*\)$/.test(s))s='-'+s.slice(1,-1);const n=Number(s);return Number.isFinite(n)?n:0};
const safeName=v=>clean(v||'All_Departments').replace(/[^A-Za-z0-9_-]+/g,'_').replace(/^_+|_+$/g,'').slice(0,80)||'All_Departments';
function filteredData(){
  const page=window.DADCapexPage,rows=page?.loadRows?.()||[],payments=page?.loadPayments?.()||window.DADCapexPaymentSchedule?.loadPayments?.()||[];
  const department=clean($('deptFilter')?.value),category=clean($('categoryFilter')?.value),priority=clean($('priorityFilter')?.value),query=clean($('searchBox')?.value).toLowerCase(),group=window.DADDepartmentGroups?.groupFor(department);
  const requests=rows.filter(r=>(!department||clean(r.cc)===department||group?.ids.includes(clean(r.cc)))&&(!category||norm(r.category)===norm(category))&&(!priority||norm(r.priority)===norm(priority))&&(!query||[r.requestId,r.department,r.cc,r.description,r.justification,r.category].some(x=>clean(x).toLowerCase().includes(query))));
  const ids=new Set(requests.map(r=>clean(r.requestId)).filter(Boolean));
  const filteredPayments=payments.filter(p=>ids.has(clean(p.requestId))&&(!query||[p.requestId,p.department,p.cc,p.description,p.paymentType,p.expectedPaymentDate,p.status,p.notes].some(x=>clean(x).toLowerCase().includes(query))));
  return{requests,payments:filteredPayments,department,category,priority,query};
}
function styleHeader(ws,count){const row=ws.getRow(1);row.height=30;for(let c=1;c<=count;c++){const cell=row.getCell(c);cell.font={bold:true,color:{argb:'FFFFFFFF'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0A2C61'}};cell.alignment={vertical:'middle',horizontal:'center',wrapText:true}}}
function styleTable(ws,widths){widths.forEach((w,i)=>ws.getColumn(i+1).width=w);ws.views=[{state:'frozen',ySplit:1}];ws.autoFilter={from:{row:1,column:1},to:{row:1,column:widths.length}};ws.eachRow((row,n)=>row.eachCell(cell=>{cell.border={bottom:{style:'thin',color:{argb:'FFDCE8E6'}},right:{style:'thin',color:{argb:'FFDCE8E6'}}};if(n>1)cell.alignment={vertical:'middle',wrapText:true}}))}
function moneyCols(ws,cols,start=2){cols.forEach(c=>{for(let r=start;r<=ws.rowCount;r++)ws.getRow(r).getCell(c).numFmt='#,##0;[Red]-#,##0;–'})}
function paymentAggregation(requests,payments){const byRequest=new Map(),pay2028=new Map();payments.forEach(p=>{const id=clean(p.requestId),date=clean(p.expectedPaymentDate),amount=num(p.amount);if(date.startsWith('2027-')){const month=Number(date.slice(5,7))-1;if(!byRequest.has(id))byRequest.set(id,Array(12).fill(0));if(month>=0&&month<12)byRequest.get(id)[month]+=amount}else if(date.startsWith('2028-'))pay2028.set(id,(pay2028.get(id)||0)+amount)});return{byRequest,pay2028}}
async function downloadReport(){
  if(typeof ExcelJS==='undefined')throw new Error('Excel report engine is still loading.');
  const{requests,payments,department,category,priority,query}=filteredData();if(!requests.length)throw new Error('No CAPEX data is available for the selected filters.');
  const wb=new ExcelJS.Workbook();wb.creator='DAD Budget 2027';wb.title='CAPEX Budget 2027 Report';wb.created=new Date();wb.calcProperties.fullCalcOnLoad=true;
  const total=requests.reduce((s,r)=>s+num(r.total),0),payments2027=payments.filter(p=>clean(p.expectedPaymentDate).startsWith('2027-')).reduce((s,p)=>s+num(p.amount),0),paymentsOutside=payments.reduce((s,p)=>s+num(p.amount),0)-payments2027,scheduled=payments.reduce((s,p)=>s+num(p.amount),0),high=requests.filter(r=>norm(r.priority)==='HIGH').length,depCount=new Set(requests.map(r=>clean(r.cc||r.department))).size;
  const summary=wb.addWorksheet('Summary');summary.addRows([
    ['CAPEX Budget 2027 Report','Value'],['Total CAPEX Requested',total],['CAPEX Requests',requests.length],['FY 2027 Payments',payments2027],['Payments Outside FY 2027',paymentsOutside],['Unscheduled Amount',total-scheduled],['High Priority Requests',high],['Departments',depCount],[],['Applied Filters',''],['Department',department||'All Departments'],['Asset Category',category||'All Categories'],['Priority',priority||'All Priorities'],['Search',query||'None'],['Generated At',new Date().toLocaleString()]
  ]);styleHeader(summary,2);summary.getColumn(1).width=32;summary.getColumn(2).width=28;moneyCols(summary,[2],2);
  const byDept=new Map();requests.forEach(r=>{const key=clean(r.cc||r.department),x=byDept.get(key)||{cc:clean(r.cc),department:clean(r.department),requests:0,total:0,high:0};x.requests++;x.total+=num(r.total);if(norm(r.priority)==='HIGH')x.high++;byDept.set(key,x)});const deptWs=wb.addWorksheet('Department Summary');deptWs.addRow(['Fund Center','Department','Requests','High Priority','FY CAPEX 2027']);[...byDept.values()].sort((a,b)=>a.department.localeCompare(b.department)||a.cc.localeCompare(b.cc)).forEach(x=>deptWs.addRow([x.cc,x.department,x.requests,x.high,x.total]));deptWs.addRow(['','TOTAL',requests.length,high,total]);styleHeader(deptWs,5);styleTable(deptWs,[18,34,14,14,20]);moneyCols(deptWs,[5]);deptWs.getRow(deptWs.rowCount).font={bold:true};
  const req=wb.addWorksheet('Order Requests');req.addRow(['Request ID','Department','Fund Center','Company','Asset Category','Budget Description','Justification','Priority','Quantity','Q1','Q2','Q3','Q4','FY CAPEX 2027']);requests.forEach(r=>req.addRow([clean(r.requestId),clean(r.department),clean(r.cc),clean(r.company),clean(r.category),clean(r.description),clean(r.justification),clean(r.priority),num(r.quantity),num(r.q1),num(r.q2),num(r.q3),num(r.q4),num(r.total)]));req.addRow(['TOTAL','','','','','','','',requests.reduce((s,r)=>s+num(r.quantity),0),requests.reduce((s,r)=>s+num(r.q1),0),requests.reduce((s,r)=>s+num(r.q2),0),requests.reduce((s,r)=>s+num(r.q3),0),requests.reduce((s,r)=>s+num(r.q4),0),total]);styleHeader(req,14);styleTable(req,[24,30,18,16,24,42,42,14,12,14,14,14,14,20]);moneyCols(req,[10,11,12,13,14]);req.getRow(req.rowCount).font={bold:true};
  const{byRequest,pay2028}=paymentAggregation(requests,payments),ps=wb.addWorksheet('Payment Schedule');ps.addRow(['Request ID','Department','Fund Center','Asset Category','Budget Description','FY CAPEX 2027',...MONTHS,'Q1','Q2','Q3','Q4','FY 2027 Payments','2028','Total Payments','Remaining']);requests.forEach(r=>{const id=clean(r.requestId),months=byRequest.get(id)||Array(12).fill(0),qs=[months.slice(0,3),months.slice(3,6),months.slice(6,9),months.slice(9,12)].map(a=>a.reduce((s,v)=>s+v,0)),fy27=months.reduce((s,v)=>s+v,0),fy28=pay2028.get(id)||0,paid=fy27+fy28;ps.addRow([id,clean(r.department),clean(r.cc),clean(r.category),clean(r.description),num(r.total),...months,...qs,fy27,fy28,paid,num(r.total)-paid])});const monthTotals=MONTHS.map((_,i)=>requests.reduce((s,r)=>s+num((byRequest.get(clean(r.requestId))||[])[i]),0)),qTotals=[monthTotals.slice(0,3),monthTotals.slice(3,6),monthTotals.slice(6,9),monthTotals.slice(9,12)].map(a=>a.reduce((s,v)=>s+v,0)),fy27Total=monthTotals.reduce((s,v)=>s+v,0),fy28Total=requests.reduce((s,r)=>s+(pay2028.get(clean(r.requestId))||0),0);ps.addRow(['TOTAL','','','','',total,...monthTotals,...qTotals,fy27Total,fy28Total,fy27Total+fy28Total,total-fy27Total-fy28Total]);styleHeader(ps,26);styleTable(ps,[24,30,18,24,42,20,...Array(12).fill(13),14,14,14,14,18,16,18,18]);moneyCols(ps,Array.from({length:21},(_,i)=>6+i));ps.getRow(ps.rowCount).font={bold:true};
  const tx=wb.addWorksheet('Payment Details');tx.addRow(['Request ID','Department','Fund Center','Budget Description','Payment No.','Payment Type','Expected Payment Date','Amount','Status','Notes']);payments.sort((a,b)=>clean(a.expectedPaymentDate).localeCompare(clean(b.expectedPaymentDate))).forEach(p=>tx.addRow([clean(p.requestId),clean(p.department),clean(p.cc),clean(p.description),clean(p.paymentNo),clean(p.paymentType),clean(p.expectedPaymentDate),num(p.amount),clean(p.status),clean(p.notes)]));tx.addRow(['TOTAL','','','','','','',scheduled,'','']);styleHeader(tx,10);styleTable(tx,[24,30,18,42,14,20,20,18,16,42]);moneyCols(tx,[8]);tx.getRow(tx.rowCount).font={bold:true};
  const buffer=await wb.xlsx.writeBuffer(),blob=new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a'),deptLabel=department&& !window.DADDepartmentGroups?.groupFor(department)?department:'All_Departments';a.href=url;a.download=`CAPEX_Budget_2027_Report_${safeName(deptLabel)}.xlsx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200)
}
function install(){
  if(!/capex\.html$/i.test((location.pathname||'').split('?')[0]))return;
  const actions=document.querySelector('.table-card .toolbar .actions');if(!actions)return setTimeout(install,120);
  if($('downloadCapexReport'))return;
  const btn=document.createElement('button');btn.type='button';btn.className='download-btn';btn.id='downloadCapexReport';btn.textContent='Download Report';const template=$('downloadTemplate');template?actions.insertBefore(btn,template):actions.appendChild(btn);btn.onclick=async()=>{const status=$('capexStatus'),old=clean(status?.textContent);try{if(status){status.textContent='Building CAPEX report...';status.classList.remove('error');status.classList.add('ready')}await downloadReport();if(status)status.textContent='CAPEX report downloaded.'}catch(e){if(status){status.textContent=old||'CAPEX report failed';status.classList.add('error')}alert(e?.message||e)}}
}
window.DADCapexReport={downloadReport};install();window.addEventListener('dad-user-ready',install);window.addEventListener('load',install);
})();