import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, createUserWithEmailAndPassword, deleteUser, signOut, onAuthStateChanged, sendPasswordResetEmail, setPersistence, browserLocalPersistence, browserSessionPersistence } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { getFirestore, doc, getDoc, getDocs, collection, setDoc, serverTimestamp, runTransaction } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyDAMLbm1ngqtzKjnDp6AMz8ucyhqNSnfBY',authDomain:'budget-8c575.firebaseapp.com',projectId:'budget-8c575',storageBucket:'budget-8c575.firebasestorage.app',messagingSenderId:'990142203884',appId:'1:990142203884:web:5c22dc2c14855528a022c9',measurementId:'G-CVGT8LE9PE'};
const MAIN_ADMIN_UID='PST3chwdZmaQGeG25t4ym9Vlixe2',MAIN_ADMIN_EMAIL='allaham@dadgroup.com';
const ALL_MODULES=['dashboard','executive','opex_detail','opex_summary','capex','travel','hr','ap','training','ims','pl','approvals','data_admin'];
const PROFILE_KEY='dadBudgetCurrentProfile';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const provisioningApp=initializeApp(firebaseConfig,'dad-budget-user-provisioning'),provisioningAuth=getAuth(provisioningApp);
let explicitSignInInProgress=false;
const pathNow=()=>((location.pathname.split('/').pop()||'index.html').toLowerCase());
const clean=v=>String(v??'').trim();
const isAdmin=p=>p?.isMainAdmin===true||p?.role==='admin';
const departmentsOf=p=>Array.isArray(p?.departments)?p.departments.map(clean).filter(Boolean):(p?.department?[clean(p.department)]:[]);

function ensureSidebarTheme(){if(document.querySelector('link[data-dad-sidebar-theme]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='css/sidebar-neon.css?v=20260817-1';l.dataset.dadSidebarTheme='1';document.head.appendChild(l)}
ensureSidebarTheme();

async function getProfile(uid){const s=await getDoc(doc(db,'users',uid));if(!s.exists())return null;const p={id:s.id,...s.data()};if(p.role==='executive_viewer'&&!(Array.isArray(p.modules)&&p.modules.includes('executive')))p.modules=[...new Set([...(Array.isArray(p.modules)?p.modules:[]),'executive'])];return p}
async function ensureMainAdminProfile(user){if(!user||user.uid!==MAIN_ADMIN_UID)return;await setDoc(doc(db,'users',user.uid),{uid:user.uid,email:(user.email||MAIN_ADMIN_EMAIL).toLowerCase(),role:'admin',isMainAdmin:true,enabled:true,department:'ALL',departments:['ALL'],departmentLabel:'All Departments',departmentLabels:['All Departments'],modules:ALL_MODULES,updatedAt:serverTimestamp()},{merge:true})}
function cleanUserProfile(uid,p={}){const main=uid===MAIN_ADMIN_UID,deps=main?['ALL']:[...new Set(departmentsOf(p))],labels=main?['All Departments']:(Array.isArray(p.departmentLabels)?p.departmentLabels.map(clean).filter(Boolean):(p.departmentLabel?[clean(p.departmentLabel)]:[]));return{uid,email:clean(p.email).toLowerCase(),role:main?'admin':clean(p.role||'department_user'),isMainAdmin:main,enabled:main?true:p.enabled!==false,department:main?'ALL':(deps[0]||''),departments:deps,departmentLabel:main?'All Departments':(labels[0]||'Not Restricted'),departmentLabels:labels,modules:main?ALL_MODULES:(Array.isArray(p.modules)?p.modules:[]),updatedAt:serverTimestamp()}}
function clearSession(){localStorage.removeItem('dadBudgetCurrentUid');localStorage.removeItem('dadBudgetCurrentEmail');localStorage.removeItem(PROFILE_KEY)}
function cacheSession(user,p){localStorage.setItem('dadBudgetCurrentUid',user.uid);localStorage.setItem('dadBudgetCurrentEmail',(user.email||'').toLowerCase());localStorage.setItem(PROFILE_KEY,JSON.stringify({uid:user.uid,email:(user.email||'').toLowerCase(),role:p.role||'',isMainAdmin:!!p.isMainAdmin,enabled:p.enabled!==false,department:p.department||'',departments:departmentsOf(p),departmentLabel:p.departmentLabel||'',departmentLabels:Array.isArray(p.departmentLabels)?p.departmentLabels:[],modules:Array.isArray(p.modules)?p.modules:[]}))}
let publicIpPromise=null;
function getPublicIp(){
  try{const cached=sessionStorage.getItem('dadBudgetPublicIp');if(cached)return Promise.resolve(cached)}catch(_){}
  if(publicIpPromise)return publicIpPromise;
  publicIpPromise=new Promise(resolve=>{let finished=false,script=null,timer=null;const callback=`dadBudgetIp_${Date.now()}_${Math.random().toString(36).slice(2)}`,done=value=>{if(finished)return;finished=true;clearTimeout(timer);try{delete window[callback];script?.remove()}catch(_){}const ip=clean(value).slice(0,80);if(ip)try{sessionStorage.setItem('dadBudgetPublicIp',ip)}catch(_){}resolve(ip)};window[callback]=data=>done(data?.ip);script=document.createElement('script');script.async=true;script.referrerPolicy='no-referrer';script.src=`https://api64.ipify.org?format=jsonp&callback=${encodeURIComponent(callback)}`;script.onerror=()=>done('');timer=setTimeout(()=>done(''),3500);document.head.appendChild(script)});
  return publicIpPromise;
}
function getDeviceId(){
  try{const saved=localStorage.getItem('dadBudgetDeviceId');if(saved)return saved}catch(_){}
  const raw=globalThis.crypto?.randomUUID?.().replace(/-/g,'').slice(0,12).toUpperCase()||`${Date.now().toString(36)}${Math.random().toString(36).slice(2)}`.slice(0,12).toUpperCase(),id=`DAD-${raw.slice(0,4)}-${raw.slice(4,8)}-${raw.slice(8,12)}`;
  try{localStorage.setItem('dadBudgetDeviceId',id)}catch(_){}
  return id;
}
function getDeviceInfo(){const platform=clean(navigator.userAgentData?.platform||navigator.platform||''),browser=clean(navigator.userAgentData?.brands?.map(x=>x.brand).filter(x=>!/^Not/i.test(x)).join(' / ')||'');return[platform,browser].filter(Boolean).join(' · ').slice(0,180)}
function moduleForPath(p){if(!p||p==='index.html')return'dashboard';if(p==='executive-command-center.html')return'executive';if(p==='ims-sales.html')return'ims';if(p==='capex.html')return'capex';if(p==='training-expense.html')return'training';if(p==='travel-budget.html')return'travel';if(p==='hr-budget.html')return'hr';if(p==='ap-budget.html')return'ap';if(p==='manager-approval.html')return'approvals';if(p==='data-admin.html')return'main_admin';if(p==='user-settings.html'||p==='activity-log.html'||p==='submission-control.html'||p==='admin-org-chart.html')return'admin_only';if(p==='opex-summary.html')return'opex_summary';if(p==='opex.html')return'opex_detail';return''}
function moduleForLink(a){const h=(a.getAttribute('href')||'').split('?')[0].toLowerCase(),t=(a.textContent||'').trim().toLowerCase();if(h.includes('executive-command-center'))return'executive';if(h.includes('data-admin'))return'main_admin';if(h.includes('user-settings')||h.includes('activity-log')||h.includes('submission-control')||h.includes('admin-org-chart'))return'admin_only';if(t.includes('assumption'))return'admin_only';if(h.includes('manager-approval'))return'approvals';if(h.includes('ims-sales'))return'ims';if(h.includes('capex'))return'capex';if(h.includes('opex-summary'))return'opex_summary';if(h.includes('training-expense'))return'training';if(h.includes('travel-budget'))return'travel';if(h.includes('hr-budget'))return'hr';if(h.includes('ap-budget'))return'ap';if(h.includes('opex'))return'opex_detail';if(h.includes('index'))return'dashboard';if(t.includes('p&l'))return'pl';if(t.includes('approval'))return'approvals';return''}
function applyAccess(p){const admin=isAdmin(p),manager=p?.role==='manager',mainAdmin=p?.isMainAdmin===true,mods=new Set(Array.isArray(p.modules)?p.modules:[]),has=req=>mods.has(req)||(manager&&req==='approvals')||(mods.has('opex')&&(req==='opex_detail'||req==='opex_summary')),nav=document.querySelector('.sidebar-nav');if(nav&&admin){let anchor=nav.querySelector('a[href="user-settings.html"]')||nav.querySelector('a[href="data-admin.html"]');if(!nav.querySelector('a[href="admin-org-chart.html"]')){const a=document.createElement('a');a.href='admin-org-chart.html';a.textContent='Org & Permissions';anchor?anchor.after(a):nav.appendChild(a);anchor=a}else anchor=nav.querySelector('a[href="admin-org-chart.html"]');if(!nav.querySelector('a[href="activity-log.html"]')){const a=document.createElement('a');a.href='activity-log.html';a.textContent='Activity Log';anchor?anchor.after(a):nav.appendChild(a)}}nav?.querySelectorAll('a').forEach(a=>{const r=moduleForLink(a);if(!r)return;const allowed=r==='main_admin'?mainAdmin:r==='admin_only'?admin:(admin||has(r));if(allowed)a.style.removeProperty('display');else a.style.setProperty('display','none','important')});const opexSub=nav?.querySelector('.opex-subnav'),opexParent=opexSub?.previousElementSibling;if(opexSub&&opexParent?.tagName==='A'){const anyChild=[...opexSub.querySelectorAll('a')].some(a=>getComputedStyle(a).display!=='none');if(admin||has('opex_detail')||anyChild)opexParent.style.removeProperty('display');else opexParent.style.setProperty('display','none','important');opexParent.href=(admin||has('opex_detail'))?'opex.html':'#'}const req=moduleForPath(pathNow()),allowed=req==='main_admin'?mainAdmin:(admin||(req!=='admin_only'&&has(req)));if(req&&!allowed&&pathNow()!=='index.html'){location.replace('index.html');return}const out=document.getElementById('logoutBtn');if(out){let b=document.getElementById('currentUserBadge');if(!b){b=document.createElement('div');b.id='currentUserBadge';b.style.cssText='display:flex;flex-direction:column;align-items:flex-end;margin-left:auto;margin-right:8px;font-size:10px;line-height:1.35;color:#557076';out.parentNode?.insertBefore(b,out)}b.innerHTML=`<b style="color:#163f46">${p.email||''}</b><span>${p.role||''}</span>`}}
function setupLogout(){const b=document.getElementById('logoutBtn');if(!b||b.dataset.fbLogout)return;b.dataset.fbLogout='1';b.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();try{await signOut(auth)}catch(_){}clearSession();location.replace('login.html')},true)}
function safeKey(v){return clean(v||'GENERAL').toUpperCase().replace(/[^A-Z0-9_-]+/g,'_').slice(0,160)||'GENERAL'}
const htmlEscape=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function auditModule(input){const id=(input?.id||'').toLowerCase(),p=pathNow();if(id.includes('ims'))return'ims';if(id.includes('capex')||p==='capex.html')return'capex';if(id.includes('training')||p==='training-expense.html')return'training';if(id.includes('travel')||p==='travel-budget.html')return'travel';if(id.includes('hr')||p==='hr-budget.html')return'hr';if(id.includes('ap')||p==='ap-budget.html')return'ap';if(id.includes('opex')||p==='opex.html')return'opex';if(p==='data-admin.html')return'data_admin';return p.replace('.html','')||'general'}
function setupUploadAudit(p){document.querySelectorAll('input[type="file"]').forEach(i=>{if(i.dataset.auditBound)return;i.dataset.auditBound='1';i.addEventListener('change',async()=>{const f=i.files?.[0];if(!f)return;const s=document.getElementById('deptFilter'),department=clean(s?.value||p.department||'GENERAL'),departmentLabel=s?.selectedOptions?.[0]?.textContent||p.departmentLabel||'';try{await window.DADFirebase.logAuditEvent({module:auditModule(i),action:'upload',department,departmentLabel,fileName:f.name,details:{fileSize:Number(f.size||0),page:pathNow()}})}catch(e){console.warn('Audit log failed:',e)}},true)})}

window.DADFirebase={app,auth,db,projectId:firebaseConfig.projectId,mainAdminUid:MAIN_ADMIN_UID,mainAdminEmail:MAIN_ADMIN_EMAIL,
async signIn(email,password,remember=false){explicitSignInInProgress=true;const normalizedEmail=clean(email).toLowerCase();try{try{await signOut(auth)}catch(_){}clearSession();await setPersistence(auth,remember?browserLocalPersistence:browserSessionPersistence);const c=await signInWithEmailAndPassword(auth,normalizedEmail,password);await ensureMainAdminProfile(c.user);const p=await getProfile(c.user.uid);if(!p){await signOut(auth);clearSession();throw new Error('This account does not have a Budget 2027 user profile yet.')}if(p.enabled===false){await signOut(auth);clearSession();throw new Error('This Budget 2027 account is disabled.')}cacheSession(c.user,p);localStorage.setItem('dadBudgetRememberMe',remember?'1':'0');if(remember)localStorage.setItem('dadBudgetRememberedEmail',normalizedEmail);else localStorage.removeItem('dadBudgetRememberedEmail');return c.user}finally{explicitSignInInProgress=false}},
async signOut(){await signOut(auth);clearSession()},onAuthStateChanged(cb){return onAuthStateChanged(auth,cb)},async getUserProfile(uid){return getProfile(uid)},
async listUserProfiles(){const s=await getDocs(collection(db,'users'));return s.docs.map(x=>({id:x.id,...x.data()}))},
async createUserAccount(email,password,p={}){if(!auth.currentUser)throw new Error('Sign in first.');const adminProfile=await getProfile(auth.currentUser.uid);if(auth.currentUser.uid!==MAIN_ADMIN_UID&&!isAdmin(adminProfile))throw new Error('Admin access is required.');const e=clean(email).toLowerCase();if(!e||!e.includes('@'))throw new Error('A valid email is required.');if(!password||String(password).length<6)throw new Error('Password must be at least 6 characters.');let cred=null;try{try{await signOut(provisioningAuth)}catch(_){}cred=await createUserWithEmailAndPassword(provisioningAuth,e,password);const uid=cred.user.uid;await setDoc(doc(db,'users',uid),cleanUserProfile(uid,{...p,email:e}),{merge:false});return{uid,email:e,path:`users/${uid}`}}catch(err){if(cred?.user){try{await deleteUser(cred.user)}catch(_){}}throw err}finally{try{await signOut(provisioningAuth)}catch(_){}}},
async saveUserProfile(uid,p){if(!auth.currentUser)throw new Error('Sign in first.');if(!uid)throw new Error('User account reference is missing.');await setDoc(doc(db,'users',uid),cleanUserProfile(uid,p),{merge:true});return`users/${uid}`},
async setUserEnabled(uid,enabled){if(!auth.currentUser)throw new Error('Sign in first.');if(uid===MAIN_ADMIN_UID&&!enabled)throw new Error('Main Admin cannot be disabled.');await setDoc(doc(db,'users',uid),{enabled:!!enabled,updatedAt:serverTimestamp()},{merge:true});return`users/${uid}`},
async sendPasswordReset(email){const e=clean(email).toLowerCase();if(!e)throw new Error('User email is required.');await sendPasswordResetEmail(auth,e);return e},
async notifyAdminBudgetUpload(info={}){const user=auth.currentUser;if(!user)throw new Error('Sign in first.');const module=clean(info.module||'Budget').toUpperCase(),cc=clean(info.cc||'GENERAL'),departmentName=clean(info.departmentName||cc),fileName=clean(info.fileName||'Workbook'),revision=Number(info.revision||1),submittedEmail=(user.email||clean(info.submittedEmail)).toLowerCase(),deviceId=getDeviceId(),subject=`Budget 2027 · ${module} uploaded · ${departmentName}`,body=`${departmentName} (${cc}) uploaded ${module} Budget 2027.\n\nFile: ${fileName}\nRevision: R${revision}\nUploaded by: ${submittedEmail}\nDevice ID: ${deviceId}\nTime: ${new Date().toLocaleString()}`,html=`<div style="font-family:Arial,sans-serif;color:#173f46"><h2 style="color:#0b8077">Budget 2027 Upload</h2><p><b>${htmlEscape(departmentName)}</b> (${htmlEscape(cc)}) uploaded <b>${htmlEscape(module)}</b> Budget 2027.</p><table style="border-collapse:collapse"><tr><td style="padding:5px 12px 5px 0"><b>File</b></td><td>${htmlEscape(fileName)}</td></tr><tr><td style="padding:5px 12px 5px 0"><b>Revision</b></td><td>R${revision}</td></tr><tr><td style="padding:5px 12px 5px 0"><b>Uploaded by</b></td><td>${htmlEscape(submittedEmail)}</td></tr><tr><td style="padding:5px 12px 5px 0"><b>Device ID</b></td><td>${htmlEscape(deviceId)}</td></tr><tr><td style="padding:5px 12px 5px 0"><b>Time</b></td><td>${htmlEscape(new Date().toLocaleString())}</td></tr></table><p>DAD Budget 2027 Planning Center</p></div>`,createdAt=serverTimestamp();const notification=doc(collection(db,'messages')),mail=doc(collection(db,'mail'));const [inside,email]=await Promise.allSettled([setDoc(notification,{kind:'notification',notificationType:'budget_upload',status:'uploaded',department:cc,departmentName,fromUid:user.uid,fromEmail:submittedEmail,toEmail:MAIN_ADMIN_EMAIL,subject,body,revision,targetUrl:module==='CAPEX'?`capex.html?department=${encodeURIComponent(cc)}`:`opex.html?department=${encodeURIComponent(cc)}`,read:false,createdAt,clientCreatedAt:new Date().toISOString()}),setDoc(mail,{to:[MAIN_ADMIN_EMAIL],notificationType:'budget_upload',createdBy:user.uid,createdByEmail:submittedEmail,department:cc,departmentName,module,fileName,revision,message:{subject,text:body,html},createdAt})]);if(inside.status==='rejected'&&email.status==='rejected')throw email.reason||inside.reason;if(email.status==='rejected')console.warn('Budget upload email was not queued:',email.reason);return{notificationCreated:inside.status==='fulfilled',emailQueued:email.status==='fulfilled'}},
async logAuditEvent(event={}){const user=auth.currentUser;if(!user)throw new Error('Sign in first.');const [p,ipAddress]=await Promise.all([getProfile(user.uid),getPublicIp()]);if(!p)throw new Error('User profile not found.');const module=clean(event.module||'general').toLowerCase(),department=clean(event.department||p.department||'GENERAL'),counter=doc(db,'audit_counters',safeKey(`${module}__${department}`)),log=doc(collection(db,'audit_logs'));let revision=1;await runTransaction(db,async tx=>{const s=await tx.get(counter);revision=(s.exists()?Number(s.data().count||0):0)+1;tx.set(counter,{module,department,count:revision,updatedAt:serverTimestamp()},{merge:true});tx.set(log,{uid:user.uid,email:(user.email||p.email||'').toLowerCase(),role:p.role||'',module,action:clean(event.action||'update'),department,departmentLabel:clean(event.departmentLabel||''),fileName:clean(event.fileName||''),revision,deviceId:getDeviceId(),deviceInfo:getDeviceInfo(),ipAddress:ipAddress||'',details:event.details&&typeof event.details==='object'?event.details:{},createdAt:serverTimestamp(),clientTime:new Date().toISOString()})});return{id:log.id,revision}},
async listAuditLogs(){const s=await getDocs(collection(db,'audit_logs'));return s.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.createdAt?.seconds||Date.parse(b.clientTime||0)/1000||0)-(a.createdAt?.seconds||Date.parse(a.clientTime||0)/1000||0))},
async bootstrapMainAdmin(){const u=auth.currentUser;if(!u)throw new Error('Sign in first.');if(u.uid!==MAIN_ADMIN_UID)throw new Error('Signed-in account is not Main Admin.');await ensureMainAdminProfile(u);return`users/${u.uid}`},
async testConnection(){const r=doc(db,'system_status','web_connection');await setDoc(r,{app:'DAD Budget 2027',projectId:firebaseConfig.projectId,status:'connected',updatedAt:serverTimestamp()},{merge:true});return r.path}}

onAuthStateChanged(auth,async user=>{const login=pathNow()==='login.html'||pathNow()==='';if(!user){clearSession();if(!login)location.replace('login.html');return}if(login&&explicitSignInInProgress)return;try{await ensureMainAdminProfile(user);const p=await getProfile(user.uid);if(!p||p.enabled===false){await signOut(auth);clearSession();if(!login)location.replace('login.html');return}cacheSession(user,p);if(login){location.replace('index.html');return}setupLogout();applyAccess(p);setupUploadAudit(p);window.dispatchEvent(new CustomEvent('dad-user-ready',{detail:{user,profile:p}}))}catch(e){console.error('Budget user session error:',e)}});
window.dispatchEvent(new CustomEvent('dad-firebase-ready',{detail:{projectId:firebaseConfig.projectId,mainAdminUid:MAIN_ADMIN_UID}}));

if(pathNow()==='opex.html'){
  import('./opex-sync-v2.js?v=20260818-keep-approved-value-1').catch(e=>console.error('OPEX sync module failed:',e));
  import('./opex-account-name-fix.js?v=20260817-account-name-fix-1').catch(e=>console.error('OPEX account name fixer failed:',e));
  import('./opex-labels.js?v=20260818-manager-chain-1').catch(e=>console.error('OPEX label updater failed:',e));
}
if(pathNow()==='submission-control.html') import('./central-progress-control.js?v=20260818-manager-chain-1').catch(e=>console.error('Central progress controls failed:',e));
if(pathNow()==='user-settings.html') import('./user-settings-auto.js?v=20260817-auto-user-1').catch(e=>console.error('Automatic user creation controls failed:',e));
if(pathNow()!=='login.html') import('./messages-nav.js?v=20260818-keep-approved-value-1').catch(e=>console.error('Messages and notifications navigation failed:',e));
if(pathNow()==='opex.html'||pathNow()==='capex.html') import('./admin-budget-exports.js?v=20260818-manager-chain-1').catch(e=>console.error('Admin budget exports failed:',e));
