(function(){
'use strict';
const YEAR=2027,MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const PROJECTS=['Sorafenib','PALBOCICLIB','Semaglutide Pen (Injectable) + Bempedoic acid','Isavuconazole','Apixaban','Brivaracetam tablet + Oral solution','Ceftazidime + Avibactam','Lisdexamfetamine','Finasteride','Ustukinumab','Rosuvastatin/ezetimibe','Denosumab'];
const DEFAULT_ROWS=PROJECTS.map(projectName=>({department:'Corporate strategic (Licensing)',projectName,unitValue:null,months2027:{},fy2028Total:null}));
const $=id=>document.getElementById(id);
const clean=v=>String(v??'').trim();
const num=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:0};
const fmt=v=>Math.abs(num(v))<.005?'—':num(v).toLocaleString(undefined,{maximumFractionDigits:0});
const profile=()=>{try{return JSON.parse(localStorage.getItem('dadBudgetCurrentProfile')||'null')}catch(_){return null}};
function isAllowed(p){const labels=[p?.departmentLabel,...(Array.isArray(p?.departmentLabels)?p.departmentLabels:[])].map(clean).join(' ').toUpperCase();return p?.isMainAdmin===true||p?.role==='admin'||labels.includes('BUSINESS DEVELOPMENT')}
function normalizeMonths(raw={}){const out={};MONTHS.forEach((m,i)=>{const key=`${YEAR}-${String(i+1).padStart(2,'0')}`,v=raw?.[key]??raw?.[m]??raw?.[`${m} ${YEAR}`];if(v!==undefined&&v!==null&&clean(v)!=='')out[key]=num(v)});return out}
function monthsTotal(raw={}){return Object.values(normalizeMonths(raw)).reduce((sum,v)=>sum+num(v),0)}
function normalizeRow(row={}){const months2027=normalizeMonths(row.months2027||row.monthly2027||{}),hasMonths=Object.keys(months2027).length>0,annual=hasMonths?monthsTotal(months2027):(row.unitValue===null||row.unitValue===undefined||clean(row.unitValue)===''?null:num(row.unitValue));return{department:clean(row.department)||'Corporate strategic (Licensing)',projectName:clean(row.projectName),unitValue:annual,months2027,fy2028Total:row.fy2028Total===null||row.fy2028Total===undefined||clean(row.fy2028Total)===''?null:num(row.fy2028Total)}}
function workbookMonths(row){const normalized=normalizeRow(row),values=MONTHS.map((m,i)=>num(normalized.months2027?.[`${YEAR}-${String(i+1).padStart(2,'0')}`]));if(values.some(v=>Math.abs(v)>.00001))return values;if(normalized.unitValue!==null&&Math.abs(num(normalized.unitValue))>.00001){values[0]=num(normalized.unitValue)}return values}
let rows=DEFAULT_ROWS.map(x=>({...x})),api=null,fs=null,loaded=false;
const licensingRef=()=>fs.doc(api.db,'system_status','licensing_budget_fy2027');
function total(){return rows.reduce((sum,row)=>sum+num(row.unitValue),0)}
function total2028(){return rows.reduce((sum,row)=>sum+num(row.fy2028Total),0)}
function status(message,error=false){const el=$('licensingStatus');el.textContent=message;el.classList.toggle('error',error);el.classList.toggle('ready',!error)}
function escapeAttr(value){return clean(value).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function updateTotals(){const value=total();$('kpiProjects').textContent=rows.length;$('kpiTotal').textContent=fmt(value);$('tableTotal').textContent=fmt(value)}
function render(){
 const body=$('licensingBody');
 body.innerHTML=rows.map((row,index)=>`<tr><td><input data-index="${index}" data-field="department" value="${escapeAttr(row.department)}"></td><td><input data-index="${index}" data-field="projectName" value="${escapeAttr(row.projectName)}"></td><td><input class="amount-input" data-index="${index}" data-field="unitValue" type="number" min="0" step="1" value="${row.unitValue===null?'':num(row.unitValue)}" placeholder="Enter value"></td><td><button class="remove-btn" data-remove="${index}" type="button">Remove</button></td></tr>`).join('')+`<tr class="total-row"><td>Total</td><td>${rows.length} Projects</td><td id="tableTotal">${fmt(total())}</td><td>JOD</td></tr>`;
 document.querySelectorAll('[data-field]').forEach(input=>input.oninput=()=>{const row=rows[Number(input.dataset.index)];row[input.dataset.field]=input.dataset.field==='unitValue'?(input.value===''?null:num(input.value)):input.value;updateTotals()});
 document.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{rows.splice(Number(button.dataset.remove),1);render()});
 updateTotals();
}
async function save(){
 const button=$('saveLicensing');button.disabled=true;status('Saving Licensing Budget...');
 try{const user=api.auth.currentUser,p=profile()||{},payloadRows=rows.map(raw=>{const row=normalizeRow(raw);return{department:clean(row.department),projectName:clean(row.projectName),unitValue:row.unitValue===null?0:num(row.unitValue),months2027:normalizeMonths(row.months2027),fy2028Total:row.fy2028Total===null?0:num(row.fy2028Total)}});await fs.setDoc(licensingRef(),{fiscalYear:YEAR,currency:'JOD',rows:payloadRows,total:payloadRows.reduce((s,r)=>s+num(r.unitValue),0),total2028:payloadRows.reduce((s,r)=>s+num(r.fy2028Total),0),updatedBy:user.uid,updatedByEmail:clean(user.email||p.email).toLowerCase(),updatedAt:fs.serverTimestamp(),clientUpdatedAt:new Date().toISOString()},{merge:false});status(`Licensing Budget saved · ${rows.length} projects · ${fmt(total())} JOD for 2027`)}catch(error){console.error(error);status('Save failed: '+(error.code||error.message),true);alert('Licensing save failed: '+(error.message||error))}finally{button.disabled=false}
}
function add(){rows.push({department:'Corporate strategic (Licensing)',projectName:'',unitValue:null,months2027:{},fy2028Total:null});render()}
function styleHeader(sheet,lastColumn){for(let column=1;column<=lastColumn;column++){const cell=sheet.getRow(1).getCell(column);cell.font={bold:true,color:{argb:'FFFFFFFF'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0A2C61'}};cell.alignment={vertical:'middle',horizontal:'center',wrapText:true}}sheet.getRow(1).height=32;sheet.views=[{state:'frozen',ySplit:1,xSplit:2}];sheet.autoFilter={from:{row:1,column:1},to:{row:1,column:lastColumn}}}
async function download(){
 if(typeof ExcelJS==='undefined'){alert('Excel engine is still loading.');return}
 const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('Licensing Budget'),headers=['Department','Project Name',...MONTHS.map(m=>`${m} ${YEAR}`),`FY ${YEAR} Total (JOD)`,'FY 2028 Total (JOD)'];sheet.addRow(headers);
 rows.forEach(raw=>{const row=normalizeRow(raw),monthly=workbookMonths(row),r=sheet.addRow([row.department,row.projectName,...monthly,'',row.fy2028Total===null?null:num(row.fy2028Total)]),rn=r.number,totalCol=MONTHS.length+3;r.getCell(totalCol).value={formula:`SUM(C${rn}:N${rn})`};for(let c=3;c<=14;c++)r.getCell(c).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFE5F3FF'}};r.getCell(16).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFFF1D6'}}});
 const totalRow=sheet.addRow(['TOTAL','',...Array(12).fill(''),'','']),rn=totalRow.number;for(let c=3;c<=16;c++){const letter=sheet.getColumn(c).letter;totalRow.getCell(c).value={formula:`SUM(${letter}2:${letter}${rn-1})`}}
 sheet.columns=[{width:36},{width:58},...MONTHS.map(()=>({width:14})),{width:20},{width:20}];for(let c=3;c<=16;c++)sheet.getColumn(c).numFmt='#,##0.00;[Red]-#,##0.00';styleHeader(sheet,16);for(let column=1;column<=16;column++){const cell=totalRow.getCell(column);cell.font={bold:true,color:{argb:'FFFFFFFF'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF082765'}}}totalRow.height=24;
 const info=workbook.addWorksheet('Instructions');info.addRow(['DAD BUDGET 2027 - LICENSING TEMPLATE']);info.addRow(['1','Enter the 2027 Licensing value in the applicable month(s) from Jan to Dec.']);info.addRow(['2',`FY ${YEAR} Total is calculated automatically from the 12 monthly columns.`]);info.addRow(['3','Enter the full FY 2028 amount in the separate FY 2028 Total column.']);info.addRow(['4','All values are in JOD. Do not change the sheet name or headers before upload.']);info.getColumn(1).width=12;info.getColumn(2).width=100;info.getRow(1).font={bold:true,size:15,color:{argb:'FF0A2C61'}};
 const buffer=await workbook.xlsx.writeBuffer(),blob=new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Licensing_Budget_2027_2028_JOD.xlsx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)
}
function headerIndex(headers,names){const normalized=headers.map(x=>clean(x).toUpperCase().replace(/\s+/g,' '));for(const name of names){const i=normalized.indexOf(clean(name).toUpperCase().replace(/\s+/g,' '));if(i>=0)return i}return-1}
async function upload(file){
 if(typeof XLSX==='undefined'){alert('Excel engine is still loading.');return}
 try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}),sheet=workbook.Sheets[workbook.SheetNames[0]],matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:true}),headerRow=matrix.findIndex(r=>headerIndex(r,['Project Name'])>=0);if(headerRow<0)throw new Error('Licensing headers were not found. Download the latest template.');const headers=matrix[headerRow]||[],departmentIx=headerIndex(headers,['Department']),projectIx=headerIndex(headers,['Project Name']),legacyIx=headerIndex(headers,['Unit Value (JOD)','Unit Value']),fy2028Ix=headerIndex(headers,['FY 2028 Total (JOD)','FY 2028 Total','2028 Total']),monthIx=MONTHS.map(m=>headerIndex(headers,[`${m} ${YEAR}`,m]));const parsed=[];for(let i=headerRow+1;i<matrix.length;i++){const r=matrix[i]||[],projectName=clean(r[projectIx]);if(!projectName||projectName.toUpperCase()==='TOTAL')continue;const department=departmentIx>=0?clean(r[departmentIx]):'Corporate strategic (Licensing)',months2027={},hasMonthlyHeaders=monthIx.some(ix=>ix>=0);monthIx.forEach((ix,m)=>{if(ix<0)return;const raw=r[ix];if(clean(raw)!=='')months2027[`${YEAR}-${String(m+1).padStart(2,'0')}`]=num(raw)});let annual=hasMonthlyHeaders?monthsTotal(months2027):null;if(!hasMonthlyHeaders&&legacyIx>=0)annual=clean(r[legacyIx])===''?null:num(r[legacyIx]);const fy2028Total=fy2028Ix>=0&&clean(r[fy2028Ix])!==''?num(r[fy2028Ix]):null;parsed.push({department:department||'Corporate strategic (Licensing)',projectName,unitValue:annual,months2027,fy2028Total})}if(!parsed.length)throw new Error('No valid Licensing project rows were found.');rows=parsed.map(normalizeRow);render();status(`${file.name} loaded · ${rows.length} projects · review and save`)}catch(error){status('Upload rejected: '+error.message,true);alert('Licensing upload rejected: '+error.message)}finally{$('licensingFile').value=''}
}
async function load(){
 if(loaded)return;api=window.DADFirebase;if(!api?.db||!api.auth?.currentUser){setTimeout(load,500);return}loaded=true;
 try{if(!isAllowed(profile()||{})){location.replace('index.html');return}fs=await import('https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js');const snapshot=await fs.getDoc(licensingRef());if(snapshot.exists()&&Array.isArray(snapshot.data()?.rows))rows=snapshot.data().rows.map(normalizeRow);render();status(snapshot.exists()?'Latest Licensing Budget loaded.':'Blank Licensing template loaded. Download the Excel template for monthly input.')}catch(error){loaded=false;status('Unable to load Licensing Budget: '+(error.code||error.message),true)}
}
$('saveLicensing').onclick=save;$('addProject').onclick=add;$('downloadLicensing').onclick=download;$('uploadLicensing').onclick=()=>$('licensingFile').click();$('licensingFile').onchange=()=>{const file=$('licensingFile').files?.[0];if(file)upload(file)};window.addEventListener('dad-user-ready',load,{once:true});setTimeout(()=>{if(window.DADFirebase?.auth?.currentUser)load()},700);
})();