(function(){
'use strict';
const YEAR=2027,MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const PROJECTS=['Sorafenib','PALBOCICLIB','Semaglutide Pen (Injectable) + Bempedoic acid','Isavuconazole','Apixaban','Brivaracetam tablet + Oral solution','Ceftazidime + Avibactam','Lisdexamfetamine','Finasteride','Ustukinumab','Rosuvastatin/ezetimibe','Denosumab'];
const DEFAULT_ROWS=PROJECTS.map(projectName=>({department:'Corporate strategic (Licensing)',projectName,unitValue:null,months2027:{},fy2028Total:null}));
const $=id=>document.getElementById(id),clean=v=>String(v??'').trim(),num=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:0},fmt=v=>Math.abs(num(v))<.005?'—':num(v).toLocaleString(undefined,{maximumFractionDigits:0});
const profile=()=>{try{return JSON.parse(localStorage.getItem('dadBudgetCurrentProfile')||'null')}catch(_){return null}};
function isAllowed(p){const labels=[p?.departmentLabel,...(Array.isArray(p?.departmentLabels)?p.departmentLabels:[])].map(clean).join(' ').toUpperCase();return p?.isMainAdmin===true||p?.role==='admin'||labels.includes('BUSINESS DEVELOPMENT')}
function esc(v){return clean(v).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function normalizeMonths(raw={}){const out={};MONTHS.forEach((m,i)=>{const key=`${YEAR}-${String(i+1).padStart(2,'0')}`,v=raw?.[key]??raw?.[m]??raw?.[`${m} ${YEAR}`];if(v!==undefined&&v!==null&&clean(v)!=='')out[key]=num(v)});return out}
function monthsTotal(raw={}){return Object.values(normalizeMonths(raw)).reduce((sum,v)=>sum+num(v),0)}
function normalizeRow(row={}){const months2027=normalizeMonths(row.months2027||row.monthly2027||{}),hasMonths=Object.keys(months2027).length>0,annual=hasMonths?monthsTotal(months2027):(row.unitValue===null||row.unitValue===undefined||clean(row.unitValue)===''?null:num(row.unitValue));return{department:clean(row.department)||'Corporate strategic (Licensing)',projectName:clean(row.projectName),unitValue:annual,months2027,fy2028Total:row.fy2028Total===null||row.fy2028Total===undefined||clean(row.fy2028Total)===''?null:num(row.fy2028Total)}}
function workbookMonths(row){const x=normalizeRow(row),values=MONTHS.map((m,i)=>num(x.months2027?.[`${YEAR}-${String(i+1).padStart(2,'0')}`]));if(values.some(v=>Math.abs(v)>.00001))return values;if(x.unitValue!==null&&Math.abs(num(x.unitValue))>.00001)values[0]=num(x.unitValue);return values}
let rows=DEFAULT_ROWS.map(normalizeRow),api=null,fs=null,loaded=false,saving=false;
const licensingRef=()=>fs.doc(api.db,'system_status','licensing_budget_fy2027');
const total=()=>rows.reduce((s,r)=>s+num(r.unitValue),0),total2028=()=>rows.reduce((s,r)=>s+num(r.fy2028Total),0);
function status(message,error=false){const el=$('licensingStatus');if(!el)return;el.textContent=message;el.classList.toggle('error',error);el.classList.toggle('ready',!error)}
function render(){const body=$('licensingBody');if(!body)return;body.innerHTML=rows.map(row=>`<tr><td>${esc(row.department)}</td><td><b>${esc(row.projectName)||'—'}</b></td><td class="amount">${fmt(row.unitValue)}</td><td class="amount">${fmt(row.fy2028Total)}</td></tr>`).join('')+`<tr class="total-row"><td>TOTAL</td><td>${rows.length} Projects</td><td>${fmt(total())}</td><td>${fmt(total2028())}</td></tr>`;if($('kpiProjects'))$('kpiProjects').textContent=rows.length;if($('kpiTotal'))$('kpiTotal').textContent=fmt(total())}
async function ensureCloud(){api=window.DADFirebase;if(!api?.db||!api.auth?.currentUser)throw Error('Secure cloud connection is not ready.');if(!fs)fs=await import('https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js')}
async function saveUploaded(fileName='Licensing workbook'){
 if(saving)return;saving=true;
 try{await ensureCloud();const user=api.auth.currentUser,p=profile()||{},payloadRows=rows.map(raw=>{const row=normalizeRow(raw);return{department:row.department,projectName:row.projectName,unitValue:row.unitValue===null?0:num(row.unitValue),months2027:normalizeMonths(row.months2027),fy2028Total:row.fy2028Total===null?0:num(row.fy2028Total)}});status(`Saving ${fileName}...`);await fs.setDoc(licensingRef(),{fiscalYear:YEAR,currency:'JOD',rows:payloadRows,total:payloadRows.reduce((s,r)=>s+num(r.unitValue),0),total2028:payloadRows.reduce((s,r)=>s+num(r.fy2028Total),0),sourceFile:clean(fileName),updatedBy:user.uid,updatedByEmail:clean(user.email||p.email).toLowerCase(),updatedAt:fs.serverTimestamp(),clientUpdatedAt:new Date().toISOString()},{merge:false});status(`${fileName} · uploaded and saved successfully · ${rows.length} projects`)}finally{saving=false}
}
function styleHeader(sheet,lastColumn){for(let column=1;column<=lastColumn;column++){const cell=sheet.getRow(1).getCell(column);cell.font={bold:true,color:{argb:'FFFFFFFF'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0A2C61'}};cell.alignment={vertical:'middle',horizontal:'center',wrapText:true}}sheet.getRow(1).height=32;sheet.views=[{state:'frozen',ySplit:1,xSplit:2}];sheet.autoFilter={from:{row:1,column:1},to:{row:1,column:lastColumn}}}
async function download(){
 if(typeof ExcelJS==='undefined'){alert('Excel engine is still loading.');return}
 const workbook=new ExcelJS.Workbook(),sheet=workbook.addWorksheet('Licensing Budget');sheet.addRow(['Department','Project Name',...MONTHS.map(m=>`${m} ${YEAR}`),`FY ${YEAR} Total (JOD)`,'FY 2028 Total (JOD)']);
 rows.forEach(raw=>{const row=normalizeRow(raw),monthly=workbookMonths(row),r=sheet.addRow([row.department,row.projectName,...monthly,'',row.fy2028Total===null?null:num(row.fy2028Total)]),rn=r.number;r.getCell(15).value={formula:`SUM(C${rn}:N${rn})`};for(let c=3;c<=14;c++)r.getCell(c).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFE5F3FF'}};r.getCell(16).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFFF1D6'}}});
 const totalRow=sheet.addRow(['TOTAL','',...Array(12).fill(''),'','']),rn=totalRow.number;for(let c=3;c<=16;c++){const letter=sheet.getColumn(c).letter;totalRow.getCell(c).value={formula:`SUM(${letter}2:${letter}${rn-1})`}}
 sheet.columns=[{width:36},{width:58},...MONTHS.map(()=>({width:14})),{width:20},{width:20}];for(let c=3;c<=16;c++)sheet.getColumn(c).numFmt='#,##0.00;[Red]-#,##0.00';styleHeader(sheet,16);for(let c=1;c<=16;c++){const cell=totalRow.getCell(c);cell.font={bold:true,color:{argb:'FFFFFFFF'}};cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF082765'}}}totalRow.height=24;
 const info=workbook.addWorksheet('Instructions');info.addRow(['DAD BUDGET 2027 - LICENSING TEMPLATE']);info.addRow(['1','Enter the 2027 Licensing value in the applicable month(s) from Jan to Dec.']);info.addRow(['2','FY 2027 Total is calculated automatically from the 12 monthly columns.']);info.addRow(['3','Enter the full FY 2028 amount in the separate FY 2028 Total column.']);info.addRow(['4','All values are in JOD. Do not change the sheet name or headers before upload.']);info.addRow(['5','Upload this workbook from the Licensing Budget page. The upload is saved automatically.']);info.getColumn(1).width=12;info.getColumn(2).width=100;info.getRow(1).font={bold:true,size:15,color:{argb:'FF0A2C61'}};
 const buffer=await workbook.xlsx.writeBuffer(),blob=new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Licensing_Budget_2027_2028_JOD.xlsx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)
}
function headerIndex(headers,names){const normalized=headers.map(x=>clean(x).toUpperCase().replace(/\s+/g,' '));for(const name of names){const i=normalized.indexOf(clean(name).toUpperCase().replace(/\s+/g,' '));if(i>=0)return i}return-1}
async function upload(file){
 if(typeof XLSX==='undefined'){alert('Excel engine is still loading.');return}
 const button=$('uploadLicensing');try{if(button){button.disabled=true;button.textContent='Uploading...'}status('Validating Licensing workbook...');const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}),sheet=workbook.Sheets[workbook.SheetNames.find(n=>clean(n).toUpperCase()==='LICENSING BUDGET')||workbook.SheetNames[0]],matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:true}),headerRow=matrix.findIndex(r=>headerIndex(r,['Project Name'])>=0);if(headerRow<0)throw Error('Licensing headers were not found. Download the latest template.');const headers=matrix[headerRow]||[],departmentIx=headerIndex(headers,['Department']),projectIx=headerIndex(headers,['Project Name']),legacyIx=headerIndex(headers,['Unit Value (JOD)','Unit Value']),fy2028Ix=headerIndex(headers,['FY 2028 Total (JOD)','FY 2028 Total','2028 Total']),monthIx=MONTHS.map(m=>headerIndex(headers,[`${m} ${YEAR}`,m]));const parsed=[];for(let i=headerRow+1;i<matrix.length;i++){const r=matrix[i]||[],projectName=clean(r[projectIx]);if(!projectName||projectName.toUpperCase()==='TOTAL')continue;const department=departmentIx>=0?clean(r[departmentIx]):'Corporate strategic (Licensing)',months2027={},hasMonthlyHeaders=monthIx.some(ix=>ix>=0);monthIx.forEach((ix,m)=>{if(ix>=0&&clean(r[ix])!=='')months2027[`${YEAR}-${String(m+1).padStart(2,'0')}`]=num(r[ix])});let annual=hasMonthlyHeaders?monthsTotal(months2027):null;if(!hasMonthlyHeaders&&legacyIx>=0)annual=clean(r[legacyIx])===''?null:num(r[legacyIx]);const fy2028Total=fy2028Ix>=0&&clean(r[fy2028Ix])!==''?num(r[fy2028Ix]):null;parsed.push({department:department||'Corporate strategic (Licensing)',projectName,unitValue:annual,months2027,fy2028Total})}if(!parsed.length)throw Error('No valid Licensing project rows were found.');rows=parsed.map(normalizeRow);render();await saveUploaded(file.name)}catch(error){console.error(error);status('Upload rejected: '+(error?.message||error),true);alert('Licensing upload rejected: '+(error?.message||error))}finally{if(button){button.disabled=false;button.textContent='Upload Workbook'}if($('licensingFile'))$('licensingFile').value=''}
}
async function load(){if(loaded)return;try{await ensureCloud();if(!isAllowed(profile()||{})){location.replace('index.html');return}loaded=true;const snapshot=await fs.getDoc(licensingRef());if(snapshot.exists()&&Array.isArray(snapshot.data()?.rows))rows=snapshot.data().rows.map(normalizeRow);render();status(snapshot.exists()?'Latest saved Licensing Budget loaded · read-only preview.':'No saved Licensing Budget yet · download the Excel template to start.')}catch(error){loaded=false;status('Unable to load Licensing Budget: '+(error?.code||error?.message||error),true)}}
if($('downloadLicensing'))$('downloadLicensing').onclick=download;if($('uploadLicensing'))$('uploadLicensing').onclick=()=>$('licensingFile')?.click();if($('licensingFile'))$('licensingFile').onchange=()=>{const file=$('licensingFile').files?.[0];if(file)upload(file)};window.addEventListener('dad-user-ready',load,{once:true});setTimeout(()=>{if(window.DADFirebase?.auth?.currentUser)load()},700);
})();