import { getApps, initializeApp } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { getFirestore, doc, getDoc, getDocs, collection, setDoc, serverTimestamp, onSnapshot } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyDAMLbm1ngqtzKjnDp6AMz8ucyhqNSnfBY',authDomain:'budget-8c575.firebaseapp.com',projectId:'budget-8c575',storageBucket:'budget-8c575.firebasestorage.app',messagingSenderId:'990142203884',appId:'1:990142203884:web:5c22dc2c14855528a022c9'};
const MAIN_ADMIN_UID='PST3chwdZmaQGeG25t4ym9Vlixe2',KEY='dadBudgetOPEXBaselineV17';
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const clean=v=>String(v??'').trim();
const LOCKED_WORKFLOW_STATES=new Set(['pending_manager','manager_approved','submitted','under_review','approved']);
let baselineUnsub=null,baselineWatchReady=false,lastBaselineVersion='';

function submissionIsLocked(data={}){
  const workflow=clean(data.workflowStatus).toLowerCase(),finance=clean(data.financeStatus).toLowerCase(),legacy=clean(data.status).toLowerCase();
  return LOCKED_WORKFLOW_STATES.has(workflow)||LOCKED_WORKFLOW_STATES.has(finance)||LOCKED_WORKFLOW_STATES.has(legacy)
}

function localModel(){try{const m=JSON.parse(localStorage.getItem(KEY)||'null');return m?.departments?m:null}catch(_){return null}}
function saveLocal(m){localStorage.setItem(KEY,JSON.stringify(m));window.dispatchEvent(new CustomEvent('dad-opex-cloud-ready',{detail:{departments:Object.keys(m.departments||{}).length}}));window.dispatchEvent(new CustomEvent('dad-opex-refresh-departments'))}
function rebuildMaster(deps){const out={};Object.values(deps||{}).forEach(d=>Object.values(d?.items||{}).forEach(x=>{const c=clean(x?.code);if(c&&!out[c])out[c]={code:c,name:clean(x?.name)||c}}));return out}
function normalizeMaster(master,deps={}){const out={};Object.values(master||{}).forEach(x=>{const c=clean(x?.code);if(c)out[c]={code:c,name:clean(x?.name)||c}});Object.entries(master||{}).forEach(([k,x])=>{const c=clean(x?.code||k);if(c&&!out[c])out[c]={code:c,name:clean(x?.name)||c}});const rebuilt=rebuildMaster(deps);Object.entries(rebuilt).forEach(([c,x])=>{if(!out[c])out[c]=x;else if((!out[c].name||out[c].name===c)&&x.name&&x.name!==c)out[c].name=x.name});return out}
function masterArray(master){return Object.values(master||{}).map(x=>({code:clean(x?.code),name:clean(x?.name||x?.code)})).filter(x=>x.code)}
function masterObject(raw){const out={};if(Array.isArray(raw))raw.forEach(x=>{const c=clean(x?.code);if(c)out[c]={code:c,name:clean(x?.name)||c}});else Object.entries(raw||{}).forEach(([k,x])=>{const c=clean(x?.code||k);if(c)out[c]={code:c,name:clean(x?.name)||c}});return out}
function bytesToBase64(bytes){let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(s)}
function base64ToBytes(s){const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
async function encode(data){const raw=JSON.stringify(data);if(typeof CompressionStream!=='undefined'){const stream=new Blob([raw]).stream().pipeThrough(new CompressionStream('gzip'));const bytes=new Uint8Array(await new Response(stream).arrayBuffer());const payload=bytesToBase64(bytes);if(new Blob([payload]).size<900000)return{encoding:'gzip-base64-v1',payload}}if(new Blob([raw]).size<900000)return{encoding:'json-v1',payload:raw};throw new Error('Department data is too large for Firestore')}
async function decode(data,id){if(!data)return null;if(data.encoding==='gzip-base64-v1'){if(typeof DecompressionStream==='undefined')throw new Error('Please use an updated Chrome or Edge browser');const stream=new Blob([base64ToBytes(data.payload||'')]).stream().pipeThrough(new DecompressionStream('gzip'));const raw=await new Response(stream).text();const d=JSON.parse(raw);return{...d,cc:clean(d.cc||id)}}if(data.encoding==='json-v1'){const d=JSON.parse(data.payload||'{}');return{...d,cc:clean(d.cc||id)}}return{...data,cc:clean(data.cc||id)}}
function profileDepartments(p){return Array.isArray(p?.departments)?p.departments.map(clean).filter(Boolean):(p?.department?[clean(p.department)]:[])}
function setStatus(text,error=false){const s=document.getElementById('opexUploadStatus');if(s){s.textContent=text;s.classList.toggle('error',!!error);s.classList.toggle('ready',!error)}}
function rebuildDropdown(model,profile){const sel=document.getElementById('deptFilter');if(!sel||!model?.departments)return;const admin=profile?.role==='admin'||profile?.isMainAdmin===true,allowed=profileDepartments(profile),set=new Set(allowed);const list=Object.values(model.departments).filter(d=>admin||allowed.includes('ALL')||set.has(clean(d.cc))).sort((a,b)=>clean(a.name||a.cc).localeCompare(clean(b.name||b.cc)));sel.innerHTML='';if(!list.length){const o=document.createElement('option');o.value='';o.textContent='No assigned OPEX department found';sel.appendChild(o);sel.disabled=true;return}for(const d of list){const o=document.createElement('option');o.value=clean(d.cc);o.textContent=`${clean(d.cc)} · ${clean(d.name||d.cc)}`;sel.appendChild(o)}const saved=localStorage.getItem('dadBudgetOPEXSelectedDept')||'';sel.value=list.some(d=>clean(d.cc)===saved)?saved:clean(list[0].cc);sel.disabled=!admin&&list.length===1;localStorage.setItem('dadBudgetOPEXSelectedDept',sel.value);sel.dispatchEvent(new Event('change',{bubbles:true}))}
function baselineVersion(data={}){const t=data.publishedAt;return `${Number(t?.seconds||0)}:${Number(t?.nanoseconds||0)}:${clean(data.fileName)}:${Number(data.accountCount||0)}`}

// Keep Finance baseline fields (Actual/Budget/LY/FY26) authoritative.
// From a department submission, carry forward only Budget 2027 inputs.
function mergeSubmissionIntoBaseline(baseline,submitted){
  if(!baseline||!submitted?.items)return baseline;
  const merged={...baseline,items:{...(baseline.items||{})}};
  Object.entries(submitted.items||{}).forEach(([key,sItem])=>{
    const code=clean(sItem?.code||key);if(!code)return;
    const existing=merged.items[code]||merged.items[key];
    if(existing){
      const submittedBudget={...(sItem?.newBudgetByMonth||{})},hasSubmittedValues=Object.values(submittedBudget).some(v=>Math.abs(Number(v)||0)>.00001),isTravel=/^60200(0[1-9]|10)$/.test(code);
      // Older department submissions may not contain the Travel sheet values.
      // Do not let that empty payload erase Finance's controlled Travel mapping.
      merged.items[code]={...existing,newBudgetByMonth:isTravel&&!hasSubmittedValues?{...(existing.newBudgetByMonth||{})}:submittedBudget};
      if(code!==key&&merged.items[key])delete merged.items[key];
    }else{
      merged.items[code]={code,name:clean(sItem?.name)||code,newBudgetByMonth:{...(sItem?.newBudgetByMonth||{})}};
    }
  });
  return merged;
}

async function publishBaseline(user,profile){const model=localModel();if(!model)return false;const deps=Object.values(model.departments||{}),ids=[];for(const d of deps){const cc=clean(d.cc);if(!cc)continue;const e=await encode({...d,cc});await setDoc(doc(db,'opex_baseline_departments',cc),{cc,name:clean(d.name||cc),encoding:e.encoding,payload:e.payload,updatedAt:serverTimestamp()},{merge:false});ids.push(cc)}const fullMaster=normalizeMaster(model.accountMaster,model.departments);await setDoc(doc(db,'opex_baseline_meta','current'),{fileName:model.fileName||'OPEX Baseline',departmentCount:ids.length,departments:ids,accountMaster:masterArray(fullMaster),accountCount:Object.keys(fullMaster).length,publishedBy:user.uid,publishedEmail:(user.email||'').toLowerCase(),publishedAt:serverTimestamp(),schemaVersion:7},{merge:false});rebuildDropdown(model,profile);setStatus(`${model.fileName||'OPEX baseline'} · saved and shared with all users · ${Object.keys(fullMaster).length} accounts`);return true}

async function loadShared(user,profile){const assigned=profileDepartments(profile);if(!assigned.length)throw new Error('No departments assigned to this user');const meta=await getDoc(doc(db,'opex_baseline_meta','current'));if(!meta.exists())throw new Error('Finance OPEX baseline is not published yet');lastBaselineVersion=baselineVersion(meta.data()||{});const deps={};for(const cc of assigned){if(cc==='ALL')continue;const b=await getDoc(doc(db,'opex_baseline_departments',cc));if(!b.exists())continue;let department=await decode(b.data(),cc);const sub=await getDoc(doc(db,'opex_budget_submissions',cc));if(sub.exists()){const submitted=await decode(sub.data(),cc);if(submitted?.items)department=mergeSubmissionIntoBaseline(department,submitted)}deps[cc]=department}if(!Object.keys(deps).length)throw new Error('Assigned department was not found in shared OPEX baseline');const sharedMaster=masterObject(meta.data()?.accountMaster),accountMaster=normalizeMaster(sharedMaster,deps);const m={fileName:meta.data().fileName||'Cloud OPEX Baseline',departments:deps,accountMaster,cloud:true,baselineVersion:lastBaselineVersion};saveLocal(m);rebuildDropdown(m,profile);setStatus(`Latest Finance OPEX loaded · ${Object.keys(accountMaster).length} accounts`);return m}

async function loadAdminView(profile){const meta=await getDoc(doc(db,'opex_baseline_meta','current'));if(!meta.exists())throw new Error('Finance OPEX baseline is not published yet');lastBaselineVersion=baselineVersion(meta.data()||{});const baselineSnap=await getDocs(collection(db,'opex_baseline_departments')),deps={};let submissionCount=0;for(const snap of baselineSnap.docs){const cc=clean(snap.id);if(!cc)continue;let department=await decode(snap.data(),cc);const sub=await getDoc(doc(db,'opex_budget_submissions',cc));if(sub.exists()){const submitted=await decode(sub.data(),cc);if(submitted?.items){department=mergeSubmissionIntoBaseline(department,submitted);submissionCount++}}deps[cc]=department}if(!Object.keys(deps).length)throw new Error('No shared OPEX departments were found');const currentMaster=masterObject(meta.data()?.accountMaster),fullMaster=normalizeMaster(currentMaster,deps);if(Object.keys(currentMaster).length<Object.keys(fullMaster).length){await setDoc(doc(db,'opex_baseline_meta','current'),{accountMaster:masterArray(fullMaster),accountCount:Object.keys(fullMaster).length,schemaVersion:7,masterUpdatedAt:serverTimestamp()},{merge:true})}const m={fileName:meta.data().fileName||'Cloud OPEX Baseline',departments:deps,accountMaster:fullMaster,cloud:true,cloudAdminView:true,submissionCount,baselineVersion:lastBaselineVersion};saveLocal(m);rebuildDropdown(m,profile);setStatus(`Latest Finance OPEX loaded · ${Object.keys(deps).length} departments · ${submissionCount} submission${submissionCount===1?'':'s'}`);return m}

async function saveSubmission(user,profile,cc,fileName,department){if(!cc||!department)throw new Error('Department submission data is missing');const admin=profile?.role==='admin'||profile?.isMainAdmin===true,allowed=profileDepartments(profile);if(!admin&&!allowed.includes(cc))throw new Error('You cannot save data for this department');const ref=doc(db,'opex_budget_submissions',cc),prev=await getDoc(ref);if(!admin&&prev.exists()&&submissionIsLocked(prev.data()||{}))throw new Error('This budget is under approval and cannot be uploaded again until it is returned.');const e=await encode({...department,cc}),revision=(prev.exists()?Number(prev.data().revision||0):0)+1;await setDoc(ref,{cc,name:clean(department.name||cc),encoding:e.encoding,payload:e.payload,fileName:clean(fileName),revision,submittedBy:user.uid,submittedEmail:(user.email||profile.email||'').toLowerCase(),submittedAt:serverTimestamp(),clientSubmittedAt:new Date().toISOString()},{merge:true});setStatus(`${fileName} · saved to cloud · R${revision}`);return revision}

async function waitAndSaveUpload(user,profile,file){const admin=user.uid===MAIN_ADMIN_UID||profile?.role==='admin'||profile?.isMainAdmin===true;if(!admin&&document.body.dataset.opexWorkflowLock==='1'){setStatus('Upload blocked while this budget is under approval',true);return}for(let i=0;i<50;i++){await new Promise(r=>setTimeout(r,400));const m=localModel();if(m?.fileName!==file.name)continue;
    if(admin){
      try{setStatus('Saving Finance OPEX and publishing to all users...');await publishBaseline(user,profile);await loadAdminView(profile);window.dispatchEvent(new CustomEvent('dad-opex-baseline-published',{detail:{fileName:file.name}}));setStatus(`${file.name} · Finance OPEX saved successfully`)}catch(e){setStatus(`Baseline save failed: ${e.code||e.message}`,true)}return;
    }
    const cc=clean(m?.lastUploadedDepartment||document.getElementById('deptFilter')?.value);if(cc&&m.departments?.[cc]){try{await saveSubmission(user,profile,cc,file.name,m.departments[cc]);window.dispatchEvent(new CustomEvent('dad-opex-submission-saved',{detail:{cc,fileName:file.name}}))}catch(e){setStatus(`Cloud save failed: ${e.code||e.message}`,true)}return}
  }setStatus('Workbook loaded locally, but cloud save timed out',true)}

function watchBaseline(user,profile,admin){if(admin||baselineUnsub)return;baselineUnsub=onSnapshot(doc(db,'opex_baseline_meta','current'),async snap=>{if(!snap.exists())return;const version=baselineVersion(snap.data()||{});if(!baselineWatchReady){baselineWatchReady=true;lastBaselineVersion=version;return}if(!version||version===lastBaselineVersion)return;lastBaselineVersion=version;try{setStatus('Finance updated OPEX · refreshing your data...');await loadShared(user,profile);setStatus('Latest Finance OPEX loaded automatically')}catch(e){setStatus(`OPEX refresh failed: ${e.code||e.message}`,true)}})}

async function run(user){try{const ps=await getDoc(doc(db,'users',user.uid));if(!ps.exists())return;const profile=ps.data()||{},admin=user.uid===MAIN_ADMIN_UID||profile.role==='admin'||profile.isMainAdmin===true;if(admin){const model=localModel();if(model&&!model.cloudAdminView)await publishBaseline(user,profile);await loadAdminView(profile)}else await loadShared(user,profile);watchBaseline(user,profile,admin);const input=document.getElementById('opexUploadInput');if(input&&!input.dataset.cloudSubmissionV4){input.dataset.cloudSubmissionV4='1';input.addEventListener('change',()=>{const f=input.files?.[0];if(f)waitAndSaveUpload(user,profile,f)},true)}}catch(e){const sel=document.getElementById('deptFilter');if(sel){sel.innerHTML=`<option value="">Cloud error: ${e.code||e.message}</option>`;sel.disabled=true}setStatus(`Cloud error: ${e.code||e.message}`,true)}}

onAuthStateChanged(auth,user=>{if(user)run(user)});
window.addEventListener('dad-user-ready',e=>{const u=e.detail?.user||auth.currentUser;if(u)run(u)});
