import {getApps} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import {getFirestore,doc,getDoc,onSnapshot,setDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const app=getApps()[0],auth=getAuth(app),db=getFirestore(app),MAIN='PST3chwdZmaQGeG25t4ym9Vlixe2';
const $=id=>document.getElementById(id),clean=v=>String(v??'').trim(),norm=v=>clean(v).toUpperCase().replace(/[^A-Z0-9]/g,''),num=v=>{let s=clean(v).replace(/,/g,'');if(/^\(.*\)$/.test(s))s='-'+s.slice(1,-1);const n=Number(s);return Number.isFinite(n)?n:0},fmt=v=>Math.abs(num(v))<.005?'—':num(v).toLocaleString(undefined,{maximumFractionDigits:2}),esc=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const MASTER=['SAP License - Second Year','SAP GxP License','SAP - Additional Licenses','SAP NTT Data Life Science Bundle - Second Year','SAP Annual Maintenance Support (AMS)','SAP - Technical Consultation Service','SAP ABAP, BASIS and Security Resource Outsourcing','SAP - Implementation Fees','SAP - Travel Accommodation & Miscellaneous','SAP - Potential Development and Customization','SAP - Impact Cost for Project Extension','SAP - Handheld Devices and Related Network Setup','SAP - Warehouse Wi-Fi Network Setup','SAP - E-Invoice'];
let user=null,profile=null,plan={sheets:{}};

function allowed(){return user&&(user.uid===MAIN||profile?.role==='admin'||profile?.isMainAdmin===true||(Array.isArray(profile?.modules)&&profile.modules.includes('capex_it')))}
function rows(){return Array.isArray(plan?.sheets?.project)?plan.sheets.project:[]}
function setStatus(text,error=false){$('status').textContent=text;$('status').className='status '+(error?'error':'ready')}
function projectMeta(){return plan?.sheets?.projectMeta&&typeof plan.sheets.projectMeta==='object'?plan.sheets.projectMeta:{}}
function render(){const q=clean($('searchBox').value).toLowerCase(),data=rows().filter(r=>!q||[r.description,r.agreementType,r.category].some(v=>clean(v).toLowerCase().includes(q))),meta=projectMeta();$('tableHead').innerHTML='<tr><th>Description</th><th>QTY</th><th>Agreement Type</th><th>Unit Value JD</th><th>Unit Value USD</th>'+MONTHS.map(m=>`<th>${m}</th>`).join('')+'<th>Total</th><th>Mapped Category</th></tr>';$('tableBody').innerHTML=data.length?data.map(r=>`<tr><td title="${esc(r.description)}">${esc(r.description)}</td><td>${fmt(r.quantity)}</td><td>${esc(r.agreementType)}</td><td>${fmt(r.unitValueJd)}</td><td>${fmt(r.unitValueUsd)}</td>${MONTHS.map((_,i)=>`<td>${fmt((r.months||[])[i])}</td>`).join('')}<td class="money">${fmt(r.total)}</td><td>${esc(r.category)}</td></tr>`).join(''):'<tr><td colspan="19" class="empty">No Project data uploaded yet.</td></tr>';$('projectTotal').textContent=fmt(rows().reduce((s,r)=>s+num(r.total),0));$('lineCount').textContent=rows().filter(r=>Math.abs(num(r.total))>.005).length.toLocaleString();$('revision').textContent=(meta.revision||plan.revision)?`R${meta.revision||plan.revision}`:'—';$('sourceFile').textContent=clean(meta.sourceFile||plan.sourceFile)||'—'}
function headerIndex(headers,names){const h=headers.map(norm);for(const name of names){const i=h.indexOf(norm(name));if(i>=0)return i}return-1}
function parseProject(ws){if(!ws)throw new Error('Project sheet is missing.');const mx=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:true}),hi=mx.findIndex(r=>headerIndex(r,['QTY'])>=0&&headerIndex(r,['Agreement Type'])>=0);if(hi<0)throw new Error('Project: headers were not found.');const h=mx[hi],quantity=headerIndex(h,['QTY']),description=headerIndex(h,['Description','Project Description'])>=0?headerIndex(h,['Description','Project Description']):quantity-1,agreementType=headerIndex(h,['Agreement Type']),jd=headerIndex(h,['Unit Value (JOD)','Unit Value JD']),usd=headerIndex(h,['Unit Value (USD)','Unit Value USD']),mis=MONTHS.map(m=>headerIndex(h,[m])),totalIndex=headerIndex(h,['Total']),categoryIndex=headerIndex(h,['Mapped Category','Category']),out=[];for(let i=hi+1;i<mx.length;i++){const r=mx[i]||[],name=clean(r[description]);if(!name||/^total$/i.test(name))continue;const months=mis.map(c=>c>=0?num(r[c]):0),total=months.reduce((s,v)=>s+v,0)||num(r[totalIndex]);out.push({description:name,quantity:num(r[quantity]),agreementType:clean(r[agreementType]),unitValueJd:num(r[jd]),unitValueUsd:num(r[usd]),months,total,category:categoryIndex>=0?clean(r[categoryIndex]):''})}return out}
async function upload(file){if(!allowed())throw new Error('Projects permission is required.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames.find(x=>norm(x)===norm('Project'))]||wb.Sheets[wb.SheetNames[0]],project=parseProject(ws),ref=doc(db,'it_budget_plans','fy2027'),previous=await getDoc(ref),old=previous.data()||{},revision=Number(old.revision||0)+1,projectRevision=Number(old.sheets?.projectMeta?.revision||0)+1,sheets={...(old.sheets||{}),project,projectMeta:{revision:projectRevision,sourceFile:file.name,updatedBy:user.uid,updatedByEmail:clean(user.email).toLowerCase(),clientUpdatedAt:new Date().toISOString()}},payload={fiscalYear:2027,sheets,revision,sourceFile:clean(old.sourceFile)||file.name,updatedBy:user.uid,updatedByEmail:clean(user.email).toLowerCase(),updatedAt:serverTimestamp(),clientUpdatedAt:new Date().toISOString()};await setDoc(ref,payload,{merge:true});plan={...old,...payload,sheets};setStatus(`${file.name} uploaded · R${projectRevision}`);render()}
function styleSheet(ws){ws.views=[{state:'frozen',ySplit:1}];ws.autoFilter={from:'A1',to:'S1'};const widths=[46,10,18,16,16,...MONTHS.map(()=>12),18,22];widths.forEach((w,i)=>ws.getColumn(i+1).width=w);ws.getRow(1).height=28;ws.getRow(1).eachCell(c=>{c.font={bold:true,color:{argb:'FFFFFFFF'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0A2C61'}};c.alignment={vertical:'middle',horizontal:'center'}});for(let r=2;r<=ws.rowCount;r++){ws.getRow(r).eachCell(c=>{c.border={bottom:{style:'thin',color:{argb:'FFDDEBE9'}}}});ws.getRow(r).getCell(3).dataValidation={type:'list',allowBlank:true,formulae:['"Subscription,Contract,Service,Project"']};for(let c=4;c<=18;c++)ws.getRow(r).getCell(c).numFmt='#,##0.00'}}
async function downloadTemplate(){if(typeof ExcelJS==='undefined')throw new Error('Excel template engine is still loading.');const wb=new ExcelJS.Workbook();wb.creator='DAD Budget 2027';wb.title='Project Budget 2027';const ws=wb.addWorksheet('Project');ws.addRow(['Description','QTY','Agreement Type','Unit Value (JOD)','Unit Value (USD)',...MONTHS,'Total','Mapped Category']);const current=new Map(rows().map(r=>[norm(r.description),r]));MASTER.forEach(name=>{const r=current.get(norm(name))||{},row=ws.addRow([name,r.quantity||null,r.agreementType||null,r.unitValueJd||null,r.unitValueUsd||null,...MONTHS.map((_,i)=>(r.months||[])[i]||null),null,r.category||null]),n=row.number;row.getCell(18).value={formula:`SUM(F${n}:Q${n})`}});rows().filter(r=>!MASTER.some(name=>norm(name)===norm(r.description))).forEach(r=>{const row=ws.addRow([r.description,r.quantity||null,r.agreementType||null,r.unitValueJd||null,r.unitValueUsd||null,...MONTHS.map((_,i)=>(r.months||[])[i]||null),null,r.category||null]),n=row.number;row.getCell(18).value={formula:`SUM(F${n}:Q${n})`}});styleSheet(ws);const readme=wb.addWorksheet('Instructions');readme.addRows([['Project Budget 2027'],['1. Enter project quantities, agreement type and monthly payment phasing.'],['2. Total is calculated automatically from January through December.'],['3. Upload this workbook only from the Projects page.'],['4. This upload does not change any other IT Planning sheet.']]);readme.getColumn(1).width=110;readme.getRow(1).font={bold:true,size:16,color:{argb:'FF0A2C61'}};const buf=await wb.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download='Project_Budget_2027_Template.xlsx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function bind(){$('searchBox').addEventListener('input',render);$('uploadBtn').addEventListener('click',()=>{if(!allowed())return alert('Projects permission is required.');$('uploadInput').click()});$('uploadInput').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;setStatus('Validating and uploading...');try{await upload(file);alert(`Project workbook uploaded successfully.\nRevision: R${projectMeta().revision}`)}catch(error){setStatus(error.message,true);alert(`Project upload failed: ${error.message}`)}finally{e.target.value=''}});$('downloadTemplate').addEventListener('click',async()=>{try{await downloadTemplate()}catch(error){alert(`Template download failed: ${error.message}`)}})}
async function start(current){if(!current||user)return;user=current;const profileSnap=await getDoc(doc(db,'users',current.uid));profile=profileSnap.exists()?profileSnap.data()||{}:{};if(!allowed()){location.replace('index.html');return}onSnapshot(doc(db,'it_budget_plans','fy2027'),snap=>{plan=snap.exists()?snap.data()||{sheets:{}}:{sheets:{}};const meta=projectMeta();setStatus(rows().length?`${meta.sourceFile||plan.sourceFile||'Existing Project data'} · R${meta.revision||plan.revision||1}`:'No Project workbook uploaded yet.');render()},e=>setStatus(`Project plan: ${e.code||e.message}`,true))}
bind();onAuthStateChanged(auth,start);window.addEventListener('dad-user-ready',e=>start(e.detail?.user||auth.currentUser));
