import {getApps,initializeApp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import {getFirestore,doc,getDoc} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyDAMLbm1ngqtzKjnDp6AMz8ucyhqNSnfBY',authDomain:'budget-8c575.firebaseapp.com',projectId:'budget-8c575',storageBucket:'budget-8c575.firebasestorage.app',messagingSenderId:'990142203884',appId:'1:990142203884:web:5c22dc2c14855528a022c9'};
const OPEX_KEY='dadBudgetOPEXBaselineV17',CACHE_KEY='dadBudgetSubscriptionsBaselineColumnsV2',CACHE_MS=30*60*1000;
const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const clean=v=>String(v??'').trim(),norm=v=>clean(v).toUpperCase().replace(/[^A-Z0-9]/g,''),num=v=>{if(typeof v==='number'&&Number.isFinite(v))return v;let s=clean(v).replace(/,/g,'');if(/^\(.*\)$/.test(s))s='-'+s.slice(1,-1);const n=Number(s);return Number.isFinite(n)?n:0},money=v=>Math.abs(num(v))<.005?'—':num(v).toLocaleString(undefined,{maximumFractionDigits:0});
let requestToken=0,bound=false,bodyObserver=null,observerBusy=false;

function localModel(){try{const m=JSON.parse(localStorage.getItem(OPEX_KEY)||'null');return m?.departments?m:null}catch(_){return null}}
function cacheRead(cc){try{const all=JSON.parse(sessionStorage.getItem(CACHE_KEY)||'{}')||{},x=all[cc];return x&&Date.now()-num(x.ts)<CACHE_MS?x.department:null}catch(_){return null}}
function cacheWrite(cc,department){try{const all=JSON.parse(sessionStorage.getItem(CACHE_KEY)||'{}')||{};all[cc]={ts:Date.now(),department};sessionStorage.setItem(CACHE_KEY,JSON.stringify(all))}catch(_){}}
function bytesFromBase64(value){const raw=atob(value||''),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function decode(raw,id){if(!raw)return null;if(raw.encoding==='gzip-base64-v1'){if(typeof DecompressionStream==='undefined')throw new Error('Please use an updated Chrome or Edge browser.');const stream=new Blob([bytesFromBase64(raw.payload)]).stream().pipeThrough(new DecompressionStream('gzip'));return{...JSON.parse(await new Response(stream).text()),cc:id}}if(raw.encoding==='json-v1')return{...JSON.parse(raw.payload||'{}'),cc:id};return{...raw,cc:id}}
async function loadDepartment(cc){const local=localModel()?.departments?.[cc];if(local)return local;const cached=cacheRead(cc);if(cached)return cached;const snap=await getDoc(doc(db,'opex_baseline_departments',cc));if(!snap.exists())return null;const department=await decode(snap.data(),cc);if(department)cacheWrite(cc,department);return department}
function latestActualMonth(departments){let latest=0;Object.values(departments||{}).forEach(d=>Object.values(d?.items||{}).forEach(item=>Object.keys(item?.actualByMonth||{}).forEach(k=>{const m=String(k).match(/^2026-(\d{2})$/);if(m)latest=Math.max(latest,Number(m[1])||0)})));return latest}
function savedOpexCutoff(){const value=clean(localStorage.getItem('dadBudgetOPEXDateTo')),m=value.match(/^2026-(\d{2})$/),month=m?Number(m[1]):0;return month>=1&&month<=12?month:0}
function chooseCutoff(departments){const monthly=latestActualMonth(departments);if(monthly)return monthly;const saved=savedOpexCutoff();if(saved)return saved;return 6}
function sumTo(map,month){let total=0;for(let m=1;m<=month;m++)total+=num(map?.[`2026-${String(m).padStart(2,'0')}`]);return total}
function isSubscriptionItem(item={},raw=''){const code=clean(item?.code||raw),name=norm(item?.name||item?.accountName||'');return ['6140006','6141410'].includes(code)||(name.includes('SUBSCRIPTION')&&(name.includes('BOOK')||name.includes('MAGAZINE')))}
function matchingItems(department,gl,accountName=''){
 const entries=Object.entries(department?.items||{}),target=clean(gl),exact=entries.filter(([raw,item])=>clean(item?.code||raw)===target).map(([,item])=>item||{});if(exact.length)return exact;
 const nameKey=norm(accountName),byName=nameKey?entries.filter(([,item])=>norm(item?.name||item?.accountName||'')===nameKey).map(([,item])=>item||{}):[];if(byName.length)return byName;
 const subscription=entries.filter(([raw,item])=>isSubscriptionItem(item,raw)).map(([,item])=>item||{});return subscription.length===1?subscription:[]
}
function historyFor(department,gl,accountName,cutoff){const items=matchingItems(department,gl,accountName);if(!items.length)return{found:false,budgetYtd:0,actualYtd:0,fy26:0};let budgetYtd=0,actualYtd=0,fy26=0;items.forEach(item=>{budgetYtd+=sumTo(item?.budgetByMonth,cutoff);const actualMap=item?.actualByMonth||{},hasMonthly=Object.keys(actualMap).some(k=>/^2026-\d{2}$/.test(k));actualYtd+=hasMonthly?sumTo(actualMap,cutoff):num(item?.actualUnperiodized);fy26+=num(item?.fyBudget)});return{found:true,budgetYtd,actualYtd,fy26}}
function rowKey(row){if(!row||row.classList.contains('total-row')||row.querySelector('.empty-state'))return null;const cc=clean(row.cells?.[0]?.querySelector('small')?.textContent),accountName=clean(row.cells?.[1]?.querySelector('b')?.textContent),gl=clean(row.cells?.[1]?.querySelector('small')?.textContent);return cc&&gl?{cc,gl,accountName,key:`${cc}|${gl}`}:null}
function stripInjected(body){body?.querySelectorAll('.sub-baseline-cell').forEach(x=>x.remove())}
function ensureHeader(){const tr=document.querySelector('.sub-table thead tr');if(!tr)return;tr.querySelectorAll('.sub-baseline-head').forEach(x=>x.remove());const heads=[...tr.children],landing=heads.find(x=>clean(x.textContent).toLowerCase()==='landing');if(!landing)return;const actual=document.createElement('th');actual.className='sub-baseline-head actual';actual.textContent='Actual YTD';const budget=document.createElement('th');budget.className='sub-baseline-head budget';budget.textContent='Budget YTD';const fy26=document.createElement('th');fy26.className='sub-baseline-head fy26';fy26.textContent='FY Budget 2026';landing.before(actual,budget,fy26)}
function ensureStyle(){if(document.getElementById('subscriptionBaselineColumnsStyle'))return;const style=document.createElement('style');style.id='subscriptionBaselineColumnsStyle';style.textContent=`
.sub-kpis{grid-template-columns:repeat(4,minmax(180px,1fr))!important}.sub-baseline-kpi{background:linear-gradient(145deg,#fff 0%,#f8fbff 55%,#e8f2ff 100%)!important}.sub-baseline-kpi:before{background:linear-gradient(#0a3568,#4f8bc6)!important}.sub-table th.sub-baseline-head.actual{background:#0d5f59}.sub-table th.sub-baseline-head.budget{background:#123f73}.sub-table th.sub-baseline-head.fy26{background:#45536b}.sub-table td.sub-baseline-cell{background:#f7faff;color:#264f75;font-weight:950;vertical-align:middle}.sub-table td.sub-baseline-cell.actual{background:#f0faf6;color:#0b6d5f}.sub-table td.sub-baseline-cell.budget{background:#f5f9ff;color:#245d93}.sub-table td.sub-baseline-cell.fy26{background:#f6f7fa;color:#48566d}.sub-table tr:hover td.sub-baseline-cell{background:#edf5ff}.sub-table tr.total-row td.sub-baseline-cell{background:#0a2f5e!important;color:#fff!important}.sub-table td.sub-baseline-empty{color:#98a5aa;font-weight:800}.sub-note .auto-ref{color:#174f82}@media(max-width:1050px){.sub-kpis{grid-template-columns:repeat(2,1fr)!important}}@media(max-width:650px){.sub-kpis{grid-template-columns:1fr!important}}
`;document.head.appendChild(style)}
function ensureKpis(){const wrap=document.querySelector('.sub-kpis');if(!wrap)return;document.getElementById('subscriptionYtdPanel')?.remove();document.getElementById('subscriptionYtdStyle')?.remove();let budget=document.getElementById('subscriptionBudgetYtd')?.closest('.sub-kpi');if(!budget){budget=document.createElement('article');budget.className='card sub-kpi sub-baseline-kpi';budget.innerHTML='<span>Budget YTD</span><strong id="subscriptionBudgetYtd">—</strong><small id="subscriptionBudgetYtdPeriod">Finance baseline</small>';wrap.appendChild(budget)}let actual=document.getElementById('subscriptionActualYtd')?.closest('.sub-kpi');if(!actual){actual=document.createElement('article');actual.className='card sub-kpi sub-baseline-kpi';actual.innerHTML='<span>Actual YTD</span><strong id="subscriptionActualYtd">—</strong><small id="subscriptionActualYtdPeriod">Finance baseline</small>';wrap.appendChild(actual)}let fy26=document.getElementById('subscriptionFy26')?.closest('.sub-kpi');if(!fy26){fy26=document.createElement('article');fy26.className='card sub-kpi sub-baseline-kpi';fy26.innerHTML='<span>FY Budget 2026</span><strong id="subscriptionFy26">—</strong><small>JOD · Finance baseline</small>';wrap.appendChild(fy26)}const order=[[document.getElementById('subscriptionTotal')?.closest('.sub-kpi'),1],[actual,2],[budget,3],[document.getElementById('subscriptionLanding')?.closest('.sub-kpi'),4],[fy26,5],[document.getElementById('subscriptionDepartments')?.closest('.sub-kpi'),6],[document.getElementById('subscriptionDetails')?.closest('.sub-kpi'),7]];order.forEach(([el,n])=>{if(el)el.style.order=n});const note=document.querySelector('.sub-note');if(note)note.innerHTML='<b>Separate control:</b> <span class="auto-ref">Actual YTD, Budget YTD and FY Budget 2026 are reference values from the Finance baseline.</span> Details stay first in this report, while Landing and Jan-Dec FY Budget 2027 remain the department planning inputs reflected to OPEX.'}
function ensureUi(){ensureStyle();ensureKpis();ensureHeader();const empty=document.querySelector('#subscriptionBody .empty-state');if(empty)empty.setAttribute('colspan','20')}
function makeCell(value,kind,rowSpan=1,found=true){const td=document.createElement('td');td.className=`sub-baseline-cell ${kind}${found?'':' sub-baseline-empty'}`;td.textContent=found?money(value):'—';if(rowSpan>1)td.rowSpan=rowSpan;return td}
function updateKpis(totals,cutoff,available){const label=cutoff?`JOD · Jan - ${MONTHS[cutoff-1]} 2026`:'Finance baseline';const budget=document.getElementById('subscriptionBudgetYtd'),actual=document.getElementById('subscriptionActualYtd'),fy26=document.getElementById('subscriptionFy26'),bp=document.getElementById('subscriptionBudgetYtdPeriod'),ap=document.getElementById('subscriptionActualYtdPeriod');if(budget)budget.textContent=available?money(totals.budgetYtd):'—';if(actual)actual.textContent=available?money(totals.actualYtd):'—';if(fy26)fy26.textContent=available?money(totals.fy26):'—';if(bp)bp.textContent=label;if(ap)ap.textContent=label}
function applyColumns(history,cutoff){const body=document.getElementById('subscriptionBody');if(!body)return;observerBusy=true;bodyObserver?.disconnect();try{stripInjected(body);ensureUi();const detailRows=[...body.querySelectorAll('tr')].filter(r=>rowKey(r)),groups=[];for(let i=0;i<detailRows.length;){const first=rowKey(detailRows[i]),rows=[detailRows[i]];let j=i+1;while(j<detailRows.length&&rowKey(detailRows[j])?.key===first.key){rows.push(detailRows[j]);j++}groups.push({meta:first,rows});i=j}const totals={budgetYtd:0,actualYtd:0,fy26:0};let available=false;groups.forEach(group=>{const h=history[group.meta.key]||{found:false,budgetYtd:0,actualYtd:0,fy26:0};if(h.found){available=true;totals.budgetYtd+=h.budgetYtd;totals.actualYtd+=h.actualYtd;totals.fy26+=h.fy26}const row=group.rows[0],landing=row.cells[3],actual=makeCell(h.actualYtd,'actual',group.rows.length,h.found),budget=makeCell(h.budgetYtd,'budget',group.rows.length,h.found),fy26=makeCell(h.fy26,'fy26',group.rows.length,h.found);landing.before(actual,budget,fy26)});const totalRow=body.querySelector('tr.total-row');if(totalRow){const landing=totalRow.cells[3],actual=makeCell(totals.actualYtd,'actual',1,available),budget=makeCell(totals.budgetYtd,'budget',1,available),fy26=makeCell(totals.fy26,'fy26',1,available);landing.before(actual,budget,fy26)}const empty=body.querySelector('.empty-state');if(empty)empty.setAttribute('colspan','20');updateKpis(totals,cutoff,available)}finally{observerBusy=false;if(bodyObserver&&document.body.contains(body))bodyObserver.observe(body,{childList:true,subtree:true})}}
async function refresh(){if(!auth.currentUser)return;ensureUi();const body=document.getElementById('subscriptionBody');if(!body)return;const metas=[...body.querySelectorAll('tr')].map(rowKey).filter(Boolean),ccs=[...new Set(metas.map(x=>x.cc))],token=++requestToken;if(!ccs.length){applyColumns({},0);return}try{const loaded=await Promise.all(ccs.map(async cc=>[cc,await loadDepartment(cc)]));if(token!==requestToken)return;const departments=Object.fromEntries(loaded.filter(([,d])=>d)),cutoff=chooseCutoff(departments),history={};metas.forEach(m=>{if(history[m.key])return;history[m.key]=departments[m.cc]?historyFor(departments[m.cc],m.gl,m.accountName,cutoff):{found:false,budgetYtd:0,actualYtd:0,fy26:0}});applyColumns(history,cutoff)}catch(error){if(token!==requestToken)return;console.warn('Subscriptions baseline columns failed',error);applyColumns({},0)}}
function bind(){ensureUi();const body=document.getElementById('subscriptionBody');if(!body)return;if(!bound){bound=true;let timer=null;bodyObserver=new MutationObserver(()=>{if(observerBusy)return;clearTimeout(timer);timer=setTimeout(refresh,35)});bodyObserver.observe(body,{childList:true,subtree:true});document.getElementById('subscriptionDept')?.addEventListener('change',()=>setTimeout(refresh,50));document.getElementById('subscriptionSearch')?.addEventListener('input',()=>setTimeout(refresh,50));document.getElementById('subscriptionHideZero')?.addEventListener('click',()=>setTimeout(refresh,50));document.getElementById('subscriptionRefresh')?.addEventListener('click',()=>setTimeout(refresh,200));window.addEventListener('storage',e=>{if(e.key===OPEX_KEY||e.key==='dadBudgetOPEXDateTo')setTimeout(refresh,80)})}setTimeout(refresh,180)}
onAuthStateChanged(auth,user=>{if(!user)return;let tries=0;const timer=setInterval(()=>{tries++;if(document.getElementById('subscriptionBody')&&document.getElementById('subscriptionDept')){clearInterval(timer);bind()}else if(tries>40)clearInterval(timer)},150)});
window.addEventListener('load',()=>setTimeout(bind,350));