(function(){
'use strict';
let busy=false,observer=null,timer=null;
const clean=v=>String(v??'').trim();
function ensureStyle(){if(document.getElementById('subscriptionsCustomLayoutStyle'))return;const s=document.createElement('style');s.id='subscriptionsCustomLayoutStyle';s.textContent=`
.sub-kpis{grid-template-columns:repeat(4,minmax(180px,1fr))!important}.sub-table th.sub-baseline-head.actual{background:#0d5f59!important}.sub-table th.sub-baseline-head.budget{background:#123f73!important}.sub-table th.sub-baseline-head.fy26{background:#45536b!important}.sub-table td.sub-baseline-cell.actual{background:#f0faf6!important;color:#0b6d5f!important}.sub-table td.sub-baseline-cell.budget{background:#f5f9ff!important;color:#245d93!important}.sub-table td.sub-baseline-cell.fy26{background:#f6f7fa!important;color:#48566d!important}.sub-table td.details-cell{background:#fffdf6!important}.sub-table th:nth-child(3){background:#6a541c!important}.sub-table tr.total-row td{background:#0a2f5e!important;color:#fff!important}@media(max-width:1050px){.sub-kpis{grid-template-columns:repeat(2,1fr)!important}}@media(max-width:650px){.sub-kpis{grid-template-columns:1fr!important}}
`;document.head.appendChild(s)}
function customizeHeader(){const tr=document.querySelector('.sub-table thead tr');if(!tr)return;const details=[...tr.children].find(x=>clean(x.textContent).toLowerCase()==='details'),landing=[...tr.children].find(x=>clean(x.textContent).toLowerCase()==='landing'),actual=[...tr.children].find(x=>x.classList.contains('sub-baseline-head')&&clean(x.textContent).toLowerCase()==='actual ytd'),budget=[...tr.children].find(x=>x.classList.contains('sub-baseline-head')&&clean(x.textContent).toLowerCase()==='budget ytd'),fy26=[...tr.children].find(x=>x.classList.contains('sub-baseline-head')&&clean(x.textContent).toLowerCase()==='fy budget 2026');if(!details||!landing||!actual||!budget||!fy26)return;actual.classList.add('actual');budget.classList.add('budget');fy26.classList.add('fy26');details.after(actual,budget,fy26,landing)}
function customizeRows(){const body=document.getElementById('subscriptionBody');if(!body)return;[...body.querySelectorAll('tr')].forEach(row=>{const actual=row.querySelector('td.sub-baseline-cell.actual'),budget=row.querySelector('td.sub-baseline-cell.budget'),fy26=row.querySelector('td.sub-baseline-cell.fy26');if(!actual||!budget||!fy26)return;const landing=fy26.previousElementSibling,details=row.querySelector('td.details-cell')||row.cells?.[2];if(!landing||!details)return;details.after(actual,budget,fy26,landing)})}
function customizeKpis(){const order=[['subscriptionTotal',1],['subscriptionActualYtd',2],['subscriptionBudgetYtd',3],['subscriptionLanding',4],['subscriptionFy26',5],['subscriptionDepartments',6],['subscriptionDetails',7]];order.forEach(([id,n])=>{const el=document.getElementById(id)?.closest('.sub-kpi');if(el)el.style.order=n})}
function customizeText(){document.getElementById('subscriptionFinancialSummary')?.remove();const shell=document.querySelector('.sub-shell'),h=shell?.querySelector('.sub-toolbar h2'),p=shell?.querySelector('.sub-toolbar p');if(h)h.textContent='Subscriptions Details & Budget';if(p)p.textContent='Details first, followed by Actual, Budget and planning values. This layout is intentionally different from the main OPEX view.'}
function apply(){if(busy)return;busy=true;observer?.disconnect();try{ensureStyle();customizeText();customizeHeader();customizeRows();customizeKpis()}finally{busy=false;const body=document.getElementById('subscriptionBody');if(observer&&body)observer.observe(body,{childList:true,subtree:true})}}
function bind(){const body=document.getElementById('subscriptionBody');if(!body)return false;if(!observer)observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(apply,35)});observer.observe(body,{childList:true,subtree:true});apply();return true}
let tries=0;const boot=setInterval(()=>{tries++;if(bind()||tries>60)clearInterval(boot)},100);window.addEventListener('load',()=>setTimeout(apply,300));
})();
