import {getApps,initializeApp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import {getAuth,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import {getFirestore,doc,getDoc,getDocs,setDoc,collection,query,orderBy,startAt,endAt,documentId,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyDAMLbm1ngqtzKjnDp6AMz8ucyhqNSnfBY',authDomain:'budget-8c575.firebaseapp.com',projectId:'budget-8c575',storageBucket:'budget-8c575.firebasestorage.app',messagingSenderId:'990142203884',appId:'1:990142203884:web:5c22dc2c14855528a022c9'};
const MAIN_ADMIN_UID='PST3chwdZmaQGeG25t4ym9Vlixe2',DOC_PREFIX='subscription_budget_',CACHE_KEY='dadBudgetSubscriptionsPlansV1',CACHE_MS=10*60*1000;
const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const clean=v=>String(v??'').trim(),key=v=>clean(v).toUpperCase().replace(/[^A-Z0-9]/g,''),num=v=>{if(typeof v==='number'&&Number.isFinite(v))return v;let s=clean(v).replace(/,/g,'');if(/^\(.*\)$/.test(s))s='-'+s.slice(1,-1);const n=Number(s);return Number.isFinite(n)?n:0},money=v=>num(v).toLocaleString(undefined,{maximumFractionDigits:0});
const monthKey=i=>`2027-${String(i+1).padStart(2,'0')}`;
let profile=null,directory=[],accounts=[],plans={},hideZero=true;
function departmentsOf(p={}){const out=Array.isArray(p.departments)?p.departments.map(clean).filter(Boolean):[];if(p.department&&!out.includes(clean(p.department)))out.push(clean(p.department));return out}
function cachedProfile(){try{return JSON.parse(localStorage.getItem('dadBudgetCurrentProfile')||'null')||null}catch(_){return null}}
function isAdmin(user,p){return !!user&&(user.uid===MAIN_ADMIN_UID||p?.isMainAdmin===true||p?.role==='admin')}
function isSubscriptionAccount(a={}){const c=clean(a.code),n=key(a.name);return ['6140006','6141410'].includes(c)||(n.includes('SUBSCRIPTION')&&(n.includes('BOOK')||n.includes('MAGAZINE')))}
function escapeHtml(v){return clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setStatus(text,error=false){const el=$('subscriptionStatus');if(!el)return;el.textContent=text;el.classList.toggle('error',error);el.classList.toggle('ready',!error)}
function cacheRead(){try{const x=JSON.parse(sessionStorage.getItem(CACHE_KEY)||'null');return x&&Date.now()-num(x.ts)<CACHE_MS?x.plans||{}:null}catch(_){return null}}
function cacheWrite(){try{sessionStorage.setItem(CACHE_KEY,JSON.stringify({ts:Date.now(),plans}))}catch(_){}}
function clearCache(){try{sessionStorage.removeItem(CACHE_KEY)}catch(_){}}
function normalizePlan(raw={},cc=''){const rows=(Array.isArray(raw.rows)?raw.rows:[]).map(r=>({...r,cc:clean(r.cc||cc),departmentName:clean(r.departmentName),gl:clean(r.gl),accountName:clean(r.accountName),details:clean(r.details),landing:num(r.landing),newBudgetByMonth:{...(r.newBudgetByMonth||{})},annual:Number.isFinite(Number(r.annual))?num(r.annual):MONTHS.reduce((s,_,i)=>s+num(r.newBudgetByMonth?.[monthKey(i)]),0)}));return{...raw,cc:clean(raw.cc||cc),rows,revision:num(raw.revision),total:rows.reduce((s,r)=>s+r.annual,0),landingTotal:rows.reduce((s,r)=>s+r.landing,0)}}
async function loadProfile(user){const local=cachedProfile();if(local&&clean(local.uid)===user.uid)return local;const s=await getDoc(doc(db,'users',user.uid));return s.exists()?s.data()||{}:{}}
async function loadReference(){const s=await getDoc(doc(db,'opex_baseline_meta','current'));if(!s.exists())throw new Error('Finance OPEX baseline is not published yet.');const data=s.data()||{},rawDir=Array.isArray(data.departmentDirectory)?data.departmentDirectory:(data.departments||[]).map(cc=>({cc,name:cc})),rawMaster=Array.isArray(data.accountMaster)?data.accountMaster:Object.entries(data.accountMaster||{}).map(([code,a])=>({code:clean(a?.code||code),name:clean(a?.name||a?.code||code)}));directory=rawDir.map(x=>({cc:clean(x.cc),name:clean(x.name||x.departmentName||x.cc)})).filter(x=>x.cc&&x.cc!=='16').sort((a,b)=>a.name.localeCompare(b.name));accounts=rawMaster.map(x=>({code:clean(x.code),name:clean(x.name||x.code)})).filter(isSubscriptionAccount).sort((a,b)=>a.code.localeCompare(b.code));if(!accounts.length)throw new Error('No Subscriptions, Books and Magazines account was found in the OPEX account master.')}
async function loadPlans(user,force=false){if(!force){const cached=cacheRead();if(cached){plans=Object.fromEntries(Object.entries(cached).map(([cc,p])=>[cc,normalizePlan(p,cc)]));return}}const admin=isAdmin(user,profile),allowed=departmentsOf(profile),out={};if(admin){const q=query(collection(db,'system_status'),orderBy(documentId()),startAt(DOC_PREFIX),endAt(`${DOC_PREFIX}\uf8ff`)),s=await getDocs(q);s.docs.forEach(x=>{const cc=clean(x.id).slice(DOC_PREFIX.length);if(cc)out[cc]=normalizePlan(x.data()||{},cc)})}else{for(const cc of allowed.filter(x=>x&&x!=='ALL')){const s=await getDoc(doc(db,'system_status',`${DOC_PREFIX}${cc}`));if(s.exists())out[cc]=normalizePlan(s.data()||{},cc)}}plans=out;cacheWrite()}
function availableDepartments(user){if(isAdmin(user,profile))return directory;const set=new Set(departmentsOf(profile));return directory.filter(x=>set.has(x.cc))}
function populateDepartments(user){const sel=$('subscriptionDept'),list=availableDepartments(user);sel.innerHTML='';if(isAdmin(user,profile)){const all=document.createElement('option');all.value='ALL';all.textContent='All Departments';sel.appendChild(all)}list.forEach(d=>{const o=document.createElement('option');o.value=d.cc;o.textContent=`${d.cc} · ${d.name}`;sel.appendChild(o)});const saved=clean(localStorage.getItem('dadBudgetSubscriptionDept'));if(saved&&[...sel.options].some(o=>o.value===saved))sel.value=saved;else if(!isAdmin(user,profile)&&list[0])sel.value=list[0].cc}
function selectedPlans(){const cc=clean($('subscriptionDept')?.value);if(cc==='ALL')return Object.values(plans);return plans[cc]?[plans[cc]]:[]}
function render(){const selected=selectedPlans(),q=clean($('subscriptionSearch')?.value).toLowerCase(),rows=selected.flatMap(p=>p.rows||[]).filter(r=>(!hideZero||Math.abs(r.annual)+Math.abs(r.landing)>.005)&&(!q||`${r.cc} ${r.departmentName} ${r.accountName} ${r.gl} ${r.details}`.toLowerCase().includes(q))).sort((a,b)=>a.departmentName.localeCompare(b.departmentName)||a.accountName.localeCompare(b.accountName)||a.details.localeCompare(b.details));const total=rows.reduce((s,r)=>s+r.annual,0),landing=rows.reduce((s,r)=>s+r.landing,0),deps=new Set(rows.map(r=>r.cc)),details=rows.filter(r=>r.details).length;$('subscriptionTotal').textContent=money(total);$('subscriptionLanding').textContent=money(landing);$('subscriptionDepartments').textContent=deps.size.toLocaleString();$('subscriptionDetails').textContent=details.toLocaleString();const body=$('subscriptionBody');if(!rows.length){body.innerHTML='<tr><td colspan="17" class="empty-state">No subscription details match the current view.</td></tr>';return}const t={landing:0,annual:0,months:Object.fromEntries(MONTHS.map((_,i)=>[monthKey(i),0]))};rows.forEach(r=>{t.landing+=r.landing;t.annual+=r.annual;MONTHS.forEach((_,i)=>t.months[monthKey(i)]+=num(r.newBudgetByMonth?.[monthKey(i)]))});body.innerHTML=rows.map(r=>`<tr><td><b>${escapeHtml(r.departmentName||r.cc)}</b><small>${escapeHtml(r.cc)}</small></td><td><b>${escapeHtml(r.accountName||r.gl)}</b><small>${escapeHtml(r.gl)}</small></td><td class="details-cell">${escapeHtml(r.details)||'—'}</td><td>${money(r.landing)}</td>${MONTHS.map((_,i)=>`<td>${money(r.newBudgetByMonth?.[monthKey(i)])}</td>`).join('')}<td class="fy27">${money(r.annual)}</td></tr>`).join('')+`<tr class="total-row"><td><b>TOTAL</b><small>${deps.size} Departments</small></td><td></td><td></td><td>${money(t.landing)}</td>${MONTHS.map((_,i)=>`<td>${money(t.months[monthKey(i)])}</td>`).join('')}<td>${money(t.annual)}</td></tr>`}
function sheetIndex(row,names){const h=row.map(x=>clean(x).toLowerCase());for(const name of names){const i=h.indexOf(name.toLowerCase());if(i>=0)return i}return-1}
function parseWorkbook(wb,expectedCc){const sn=wb.SheetNames.find(n=>/^(subscriptions budget|subscriptions)$/i.test(clean(n)));if(!sn)throw new Error('Subscriptions Budget sheet is missing.');const mx=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:'',raw:true}),hi=mx.findIndex(r=>sheetIndex(r,['Fund Center'])>=0&&sheetIndex(r,['G/L Account','GL Account'])>=0&&sheetIndex(r,['Details'])>=0&&sheetIndex(r,['Jan'])>=0&&sheetIndex(r,['Dec'])>=0);if(hi<0)throw new Error('Subscriptions Budget headers are not valid. Download the latest template.');const h=mx[hi],ci=sheetIndex(h,['Fund Center']),gi=sheetIndex(h,['G/L Account','GL Account']),ni=sheetIndex(h,['Account Name']),di=sheetIndex(h,['Details']),li=sheetIndex(h,['Landing']),mis=MONTHS.map(m=>sheetIndex(h,[m])),allowedAccounts=Object.fromEntries(accounts.map(a=>[a.code,a])),dept=directory.find(x=>x.cc===expectedCc),rows=[];for(let i=hi+1;i<mx.length;i++){const r=mx[i]||[],cc=clean(r[ci]),gl=clean(r[gi]),details=clean(r[di]),landing=li>=0?num(r[li]):0,months=Object.fromEntries(MONTHS.map((_,mi)=>[monthKey(mi),mis[mi]>=0?num(r[mis[mi]]):0])),annual=MONTHS.reduce((s,_,mi)=>s+num(months[monthKey(mi)]),0),active=Math.abs(landing)+Math.abs(annual)>.00001;if(!active&&!details&&!gl)continue;if(cc!==expectedCc)throw new Error(`Subscriptions row ${i+1}: Fund Center must be ${expectedCc}.`);if(!allowedAccounts[gl])throw new Error(`Subscriptions row ${i+1}: G/L ${gl||'(blank)'} is not an approved Subscriptions account.`);if(active&&!details)throw new Error(`Subscriptions row ${i+1}: Details are required when a value is entered.`);if(!active)continue;rows.push({cc,departmentName:dept?.name||expectedCc,gl,accountName:allowedAccounts[gl]?.name||clean(ni>=0?r[ni]:'')||gl,details,landing,newBudgetByMonth:months,annual})}if(!rows.length)throw new Error('Subscriptions Budget is empty. Fill at least one row with Details and a value.');return rows}
function aggregateItems(rows){const out={};rows.forEach(r=>{const x=out[r.gl]||(out[r.gl]={code:r.gl,name:r.accountName,landing:0,newBudgetByMonth:{},total:0});x.landing+=r.landing;x.total+=r.annual;MONTHS.forEach((_,i)=>{const k=monthKey(i);x.newBudgetByMonth[k]=(x.newBudgetByMonth[k]||0)+num(r.newBudgetByMonth?.[k])})});return out}
function applyToDepartment(department,plan){const merged={...department,items:{...(department.items||{})},subscriptionRows:(plan.rows||[]).map(r=>({...r,newBudgetByMonth:{...(r.newBudgetByMonth||{})}}))};Object.entries(plan.items||{}).forEach(([rawGl,v])=>{const gl=clean(v.code||rawGl);let found=Object.keys(merged.items).find(k=>clean(merged.items[k]?.code||k)===gl);if(!found)found=Object.keys(merged.items).find(k=>isSubscriptionAccount(merged.items[k]||{code:k}));const existing=found?merged.items[found]:{code:gl,name:clean(v.name)||gl,budgetByMonth:{},actualByMonth:{},lyByMonth:{},newBudgetByMonth:{},fyBudget:0,actualUnperiodized:0,lyUnperiodized:0,hasLY:false},target=found||gl;merged.items[target]={...existing,code:clean(existing.code||gl),name:clean(existing.name||v.name)||gl,landing:num(v.landing),newBudgetByMonth:{...(v.newBudgetByMonth||{})},subscriptionControlled:true,subscriptionSource:'department',subscriptionDetailsCount:(plan.rows||[]).filter(r=>clean(r.gl)===gl).length}});return merged}
async function decodeSubmission(raw){if(!raw?.payload)return null;if(raw.encoding==='json-v1')return JSON.parse(raw.payload||'{}');if(raw.encoding==='gzip-base64-v1'){if(typeof DecompressionStream==='undefined')return null;const b=atob(raw.payload||''),bytes=new Uint8Array(b.length);for(let i=0;i<b.length;i++)bytes[i]=b.charCodeAt(i);const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text())}return null}
function bytesToBase64(bytes){let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(s)}
async function encodeSubmission(data){const raw=JSON.stringify(data);if(typeof CompressionStream!=='undefined'){const stream=new Blob([raw]).stream().pipeThrough(new CompressionStream('gzip'));const bytes=new Uint8Array(await new Response(stream).arrayBuffer()),payload=bytesToBase64(bytes);if(new Blob([payload]).size<900000)return{encoding:'gzip-base64-v1',payload}}if(new Blob([raw]).size<900000)return{encoding:'json-v1',payload:raw};throw new Error('OPEX submission is too large after adding Subscriptions.')}
async function prepareOpexSubmission(cc,plan){const ref=doc(db,'opex_budget_submissions',cc),snap=await getDoc(ref);if(!snap.exists())return;const raw=snap.data()||{},state=clean(raw.workflowStatus||raw.status).toLowerCase();if(['pending_manager','manager_approved','submitted','under_review','approved'].includes(state))throw new Error('This OPEX budget is already under approval. Return it first before changing Subscriptions.');const decoded=await decodeSubmission(raw);if(!decoded?.items)return;const patched=applyToDepartment(decoded,plan),encoded=await encodeSubmission(patched);await setDoc(ref,{encoding:encoded.encoding,payload:encoded.payload,workflowStatus:'uploaded',status:'uploaded',financeStatus:'not_submitted',subscriptionRows:patched.subscriptionRows||[],subscriptionUpdatedAt:serverTimestamp(),subscriptionUpdatedBy:auth.currentUser.uid,subscriptionUpdatedByEmail:clean(auth.currentUser.email).toLowerCase()},{merge:true})}
function setWidths(ws,widths){ws['!cols']=widths.map(w=>({wch:w}))}
function downloadTemplate(){const cc=clean($('subscriptionDept')?.value);if(!cc||cc==='ALL'){alert('Select one individual department first.');return}const d=directory.find(x=>x.cc===cc);if(!d)return;const wb=XLSX.utils.book_new(),iw=XLSX.utils.aoa_to_sheet([['DAD BUDGET 2027 - SUBSCRIPTIONS'],['Department',d.name],['Fund Center',cc],[],['HOW TO USE'],['1','Enter each subscription on a separate row.'],['2','Details are mandatory for every row with Landing or FY Budget 2027 values.'],['3','Use only the approved Subscriptions G/L account(s) listed in the Accounts sheet.'],['4','Jan-Dec values are reflected automatically into OPEX; Details stay in the separate Subscriptions Report.'],['5','Uploading replaces this department\'s current Subscriptions plan.']]);setWidths(iw,[20,95]);XLSX.utils.book_append_sheet(wb,iw,'Instructions');const h=['Fund Center','Department','G/L Account','Account Name','Details','Landing',...MONTHS,'FY Budget 2027'],data=[h],defaultAccount=accounts.length===1?accounts[0]:null;for(let i=0;i<50;i++)data.push([cc,d.name,defaultAccount?.code||'',defaultAccount?.name||'','','',...Array(12).fill(''),'']);const ws=XLSX.utils.aoa_to_sheet(data);for(let r=2;r<=data.length;r++)ws[`S${r}`]={t:'n',f:`SUM(G${r}:R${r})`};ws['!autofilter']={ref:`A1:S${data.length}`};setWidths(ws,[18,34,15,36,44,14,...Array(12).fill(12),17]);XLSX.utils.book_append_sheet(wb,ws,'Subscriptions Budget');const as=XLSX.utils.aoa_to_sheet([['G/L Account','Account Name'],...accounts.map(a=>[a.code,a.name])]);setWidths(as,[18,55]);XLSX.utils.book_append_sheet(wb,as,'Accounts');XLSX.writeFile(wb,`Subscriptions_Budget_2027_${d.name.replace(/[^A-Za-z0-9]+/g,'_')}_${cc}.xlsx`)}
async function savePlan(file){const cc=clean($('subscriptionDept')?.value);if(!cc||cc==='ALL')throw new Error('Select one individual department before upload.');setStatus('Validating Subscriptions workbook...');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),rows=parseWorkbook(wb,cc),prev=plans[cc]||{},items=aggregateItems(rows),payload={cc,departmentName:directory.find(x=>x.cc===cc)?.name||cc,fiscalYear:2027,currency:'JOD',rows,items,total:rows.reduce((s,r)=>s+r.annual,0),landingTotal:rows.reduce((s,r)=>s+r.landing,0),revision:num(prev.revision)+1,sourceFile:file.name,updatedBy:auth.currentUser.uid,updatedByEmail:clean(auth.currentUser.email).toLowerCase(),updatedAt:serverTimestamp(),clientUpdatedAt:new Date().toISOString()};await prepareOpexSubmission(cc,payload);await setDoc(doc(db,'system_status',`${DOC_PREFIX}${cc}`),payload,{merge:false});plans[cc]=normalizePlan({...payload,updatedAt:null},cc);cacheWrite();try{localStorage.setItem('dadBudgetSubscriptionsRefreshToken',String(Date.now()))}catch(_){}render();setStatus(`${file.name} · saved · R${plans[cc].revision} · reflected to OPEX`)}
async function boot(user){if(!user){location.href='login.html';return}try{profile=await loadProfile(user);if(profile?.enabled===false){location.href='index.html';return}await loadReference();if(!isAdmin(user,profile)&&!departmentsOf(profile).filter(x=>x!=='ALL').length){$('subscriptionContent').classList.add('hidden');$('subscriptionAccessDenied').classList.remove('hidden');return}await loadPlans(user);populateDepartments(user);render();setStatus('Subscriptions loaded · low-read mode');$('subscriptionDept').onchange=()=>{localStorage.setItem('dadBudgetSubscriptionDept',$('subscriptionDept').value);render()};$('subscriptionSearch').oninput=render;$('subscriptionHideZero').onclick=()=>{hideZero=!hideZero;$('subscriptionHideZero').textContent=`Hide Zero: ${hideZero?'ON':'OFF'}`;$('subscriptionHideZero').classList.toggle('off',!hideZero);render()};$('subscriptionDownload').onclick=downloadTemplate;$('subscriptionUpload').onclick=()=>$('subscriptionUploadInput').click();$('subscriptionUploadInput').onchange=async()=>{const f=$('subscriptionUploadInput').files?.[0];if(!f)return;try{$('subscriptionUpload').disabled=true;await savePlan(f)}catch(error){console.error(error);setStatus(`Upload failed: ${error.message||error}`,true);alert('Subscriptions upload rejected: '+(error.message||error))}finally{$('subscriptionUpload').disabled=false;$('subscriptionUploadInput').value=''}};$('subscriptionRefresh').onclick=async()=>{try{$('subscriptionRefresh').disabled=true;clearCache();await loadPlans(user,true);render();setStatus('Subscriptions refreshed')}catch(e){setStatus(`Refresh failed: ${e.message||e}`,true)}finally{$('subscriptionRefresh').disabled=false}};$('logoutBtn').onclick=async()=>{await signOut(auth);location.href='login.html'}}catch(error){console.error(error);setStatus(`Subscriptions could not load: ${error.code||error.message||error}`,true)}}
onAuthStateChanged(auth,boot);
