import {getApps,initializeApp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import {getAuth,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import {getFirestore,collection,doc,getDoc,getDocs,setDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyDAMLbm1ngqtzKjnDp6AMz8ucyhqNSnfBY',authDomain:'budget-8c575.firebaseapp.com',projectId:'budget-8c575',storageBucket:'budget-8c575.firebasestorage.app',messagingSenderId:'990142203884',appId:'1:990142203884:web:5c22dc2c14855528a022c9'};
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const MAIN_ADMIN_UID='PST3chwdZmaQGeG25t4ym9Vlixe2',ENGINEERING_CC='1000100301',MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const maintenance=new URLSearchParams(location.search).get('plan')==='maintenance';
const CFG=maintenance?{name:'Maintenance',prefix:'604',planId:'maintenance_budget_fy2027',sheet:'Maintenance Budget',file:'Maintenance_Budget_2027_Engineering.xlsx',cache:'dadBudgetMaintenancePlanCacheV1',meta:'dadBudgetMaintenanceMetaCacheV1',event:'dad-maintenance-budget-updated',token:'dadBudgetMaintenanceRefreshToken'}:{name:'Utilities',prefix:'608',planId:'utilities_budget_fy2027',sheet:'Utilities Budget',file:'Utilities_Budget_2027_Engineering.xlsx',cache:'dadBudgetUtilitiesPlanCacheV1',meta:'dadBudgetUtilitiesMetaCacheV1',event:'dad-utilities-budget-updated',token:'dadBudgetUtilitiesRefreshToken'};
const CACHE_MS=10*60*1000,META_CACHE_MS=30*60*1000,$=id=>document.getElementById(id),clean=v=>String(v??'').trim();
const num=v=>{if(typeof v==='number'&&Number.isFinite(v))return v;let s=clean(v).replace(/,/g,'');if(/^\(.*\)$/.test(s))s='-'+s.slice(1,-1);const n=Number(s);return Number.isFinite(n)?n:0},money=v=>num(v).toLocaleString(undefined,{maximumFractionDigits:0});
let profile=null,directory=[],centralAccounts=[],references=new Map(),plan={rows:[],revision:0,total:0,sourceFile:''},hideZero=true,referenceWarning='';

function cachedProfile(){try{return JSON.parse(localStorage.getItem('dadBudgetCurrentProfile')||'null')||null}catch(_){return null}}
function profileDepartments(p){return Array.isArray(p?.departments)?p.departments.map(clean):p?.department?[clean(p.department)]:[]}
function canManage(user,p){const deps=profileDepartments(p);return !!user&&(user.uid===MAIN_ADMIN_UID||p?.isMainAdmin===true||p?.role==='admin'||deps.includes(ENGINEERING_CC)||deps.includes('100100301'))}
function setStatus(text,error=false){const el=$('utilityStatus');if(!el)return;el.textContent=text;el.classList.toggle('error',error);el.classList.toggle('ready',!error)}
function cacheRead(key,maxAge=CACHE_MS){try{const x=JSON.parse(sessionStorage.getItem(key)||'null');return x&&Date.now()-num(x.ts)<maxAge?x:null}catch(_){return null}}
function cacheWrite(key,data){try{sessionStorage.setItem(key,JSON.stringify({ts:Date.now(),...data}))}catch(_){}}
function annual(months){return Object.entries(months||{}).reduce((s,[k,v])=>String(k).startsWith('2027-')?s+num(v):s,0)}
function monthKey(i){return `2027-${String(i+1).padStart(2,'0')}`}
function escapeHtml(v){return clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function byCc(){return Object.fromEntries(directory.map(x=>[clean(x.cc),x]))}
function byGl(){return Object.fromEntries(centralAccounts.map(x=>[clean(x.code),x]))}
function bytes(s){const b=atob(s||''),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
async function decode(raw,id){if(!raw)return null;if(raw.encoding==='gzip-base64-v1'){if(typeof DecompressionStream==='undefined')throw new Error('This browser cannot decode the Finance reference data.');const stream=new Blob([bytes(raw.payload)]).stream().pipeThrough(new DecompressionStream('gzip'));return{...JSON.parse(await new Response(stream).text()),cc:id}}if(raw.encoding==='json-v1')return{...JSON.parse(raw.payload||'{}'),cc:id};return{...raw,cc:id}}
function sumValues(map){return Object.values(map||{}).reduce((s,v)=>s+num(v),0)}
function referenceFor(item){return{budgetYtd:sumValues(item?.budgetByMonth),actualYtd:sumValues(item?.actualByMonth)+num(item?.actualUnperiodized),fyBudget:num(item?.fyBudget)}}

function configurePage(){
 document.title=`${CFG.name} Budget 2027 - DAD Budget`;
 const nav=document.querySelector('.opex-subnav');if(nav){nav.querySelectorAll('a').forEach(a=>a.classList.remove('active'));let m=nav.querySelector('[data-maintenance-nav]');if(!m){m=document.createElement('a');m.href='utilities.html?plan=maintenance';m.textContent='Maintenance';m.dataset.maintenanceNav='1';const u=[...nav.querySelectorAll('a')].find(a=>clean(a.textContent)==='Utilities');u?u.insertAdjacentElement('afterend',m):nav.appendChild(m)}const active=[...nav.querySelectorAll('a')].find(a=>maintenance?a.dataset.maintenanceNav==='1':clean(a.textContent)==='Utilities');active?.classList.add('active')}
 const denied=$('utilityAccessDenied');if(denied)denied.textContent=`${CFG.name} Budget is centrally maintained by Engineering (Fund Center ${ENGINEERING_CC}) and Finance Admin.`;
 const h1=document.querySelector('.utilities-head h1'),intro=document.querySelector('.utilities-head p'),totalLabel=document.querySelector('#utilityTotal')?.previousElementSibling,accountLabel=document.querySelector('#utilityAccounts')?.previousElementSibling,toolbarTitle=document.querySelector('.utility-toolbar h2'),toolbarText=document.querySelector('.utility-toolbar p'),note=document.querySelector('.utility-note');
 if(h1)h1.textContent=`${CFG.name} Budget 2027`;if(intro)intro.textContent=`Engineering enters ${CFG.name} once and allocates Landing and Budget 2027 by target Fund Center. Values are reflected automatically into each department's ${CFG.prefix}xxxx OPEX accounts.`;
 if(totalLabel)totalLabel.textContent=`Total ${CFG.name} FY 2027`;if(accountLabel)accountLabel.textContent=`${CFG.name} G/L Accounts`;if(toolbarTitle)toolbarTitle.textContent='Department Allocation & Comparison';if(toolbarText)toolbarText.textContent=`Budget YTD, Actual YTD, FY Budget 2026, Landing and monthly ${CFG.name} allocation by department.`;
 if(note)note.innerHTML=`<b>Central control:</b> ${CFG.name} G/Ls ${CFG.prefix}xxxx are entered only here. The Excel file includes every department and every ${CFG.prefix}xxxx account; each row is transferred to its own Target Fund Center.`;
 $('utilityStatus').textContent=`Loading ${CFG.name}...`;$('utilityUpload').textContent=`Upload ${CFG.name}`;
}

async function loadProfile(user){const local=cachedProfile();if(local&&(local.email?clean(local.email).toLowerCase()===clean(user.email).toLowerCase():true))return local;const snap=await getDoc(doc(db,'users',user.uid));return snap.exists()?snap.data()||{}:{}}
async function loadReferences(){references=new Map();referenceWarning='';try{const snap=await getDocs(collection(db,'opex_baseline_departments'));await Promise.all(snap.docs.map(async d=>{const dep=await decode(d.data(),d.id);Object.entries(dep?.items||{}).forEach(([raw,item])=>{const gl=clean(item?.code||raw);if(gl.startsWith(CFG.prefix))references.set(`${clean(d.id)}|${gl}`,referenceFor(item))})}))}catch(error){console.warn(`${CFG.name} comparison data could not load`,error);referenceWarning=' · comparison reference unavailable'}}
async function loadReference(){const cached=cacheRead(CFG.meta,META_CACHE_MS);if(cached?.directory&&cached?.accounts){directory=cached.directory;centralAccounts=cached.accounts;await loadReferences();return}const snap=await getDoc(doc(db,'opex_baseline_meta','current'));if(!snap.exists())throw new Error('Finance OPEX baseline is not published yet.');const data=snap.data()||{},rawDirectory=Array.isArray(data.departmentDirectory)?data.departmentDirectory:(data.departments||[]).map(cc=>({cc,name:cc})),master=Array.isArray(data.accountMaster)?data.accountMaster:Object.entries(data.accountMaster||{}).map(([code,x])=>({code:clean(x?.code||code),name:clean(x?.name||x?.code||code)}));directory=rawDirectory.map(x=>({cc:clean(x?.cc),name:clean(x?.name||x?.departmentName||x?.cc)})).filter(x=>x.cc&&x.cc!=='16').sort((a,b)=>a.name.localeCompare(b.name));centralAccounts=master.map(x=>({code:clean(x?.code),name:clean(x?.name||x?.code)})).filter(x=>x.code.startsWith(CFG.prefix)).sort((a,b)=>a.code.localeCompare(b.code));cacheWrite(CFG.meta,{directory,accounts:centralAccounts});await loadReferences()}
async function loadPlan(force=false){const cached=!force&&cacheRead(CFG.cache);if(cached?.plan){plan=cached.plan;normalizePlan();return}const snap=await getDoc(doc(db,'system_status',CFG.planId));plan=snap.exists()?snap.data()||{}:{rows:[],revision:0,total:0,sourceFile:''};normalizePlan();cacheWrite(CFG.cache,{plan})}
function normalizePlan(){plan={...plan,rows:Array.isArray(plan?.rows)?plan.rows:[],revision:num(plan?.revision),total:num(plan?.total),sourceFile:clean(plan?.sourceFile)};plan.rows=plan.rows.map(r=>({...r,cc:clean(r?.cc),departmentName:clean(r?.departmentName),gl:clean(r?.gl),accountName:clean(r?.accountName),details:clean(r?.details),landing:num(r?.landing),newBudgetByMonth:{...(r?.newBudgetByMonth||{})},annual:Number.isFinite(Number(r?.annual))?num(r.annual):annual(r?.newBudgetByMonth)})).filter(r=>r.cc&&r.gl.startsWith(CFG.prefix))}

function aggregateRows(){const map={};directory.forEach(d=>map[d.cc]={cc:d.cc,name:d.name,budgetYtd:0,actualYtd:0,fyBudget:0,landing:0,months:Object.fromEntries(MONTHS.map((_,i)=>[monthKey(i),0])),annual:0});references.forEach((ref,key)=>{const x=map[key.split('|')[0]];if(x){x.budgetYtd+=num(ref.budgetYtd);x.actualYtd+=num(ref.actualYtd);x.fyBudget+=num(ref.fyBudget)}});plan.rows.forEach(r=>{const cc=clean(r.cc);if(!cc)return;const x=map[cc]||(map[cc]={cc,name:clean(r.departmentName)||cc,budgetYtd:0,actualYtd:0,fyBudget:0,landing:0,months:Object.fromEntries(MONTHS.map((_,i)=>[monthKey(i),0])),annual:0});x.landing+=num(r.landing);MONTHS.forEach((_,i)=>x.months[monthKey(i)]+=num(r.newBudgetByMonth?.[monthKey(i)]));x.annual+=num(r.annual)});return Object.values(map)}
function render(){const rows=aggregateRows(),q=clean($('utilitySearch')?.value).toLowerCase(),visible=rows.filter(x=>(!hideZero||Math.abs(x.budgetYtd)+Math.abs(x.actualYtd)+Math.abs(x.fyBudget)+Math.abs(x.annual)+Math.abs(x.landing)>.005)&&(!q||`${x.cc} ${x.name}`.toLowerCase().includes(q))).sort((a,b)=>b.annual-a.annual||a.name.localeCompare(b.name)),total=plan.rows.reduce((s,r)=>s+num(r.annual),0),deps=new Set(plan.rows.filter(r=>Math.abs(num(r.annual))+Math.abs(num(r.landing))>.005).map(r=>r.cc)),accounts=new Set(plan.rows.filter(r=>Math.abs(num(r.annual))+Math.abs(num(r.landing))>.005).map(r=>r.gl));$('utilityTotal').textContent=money(total);$('utilityDepartments').textContent=deps.size.toLocaleString();$('utilityAccounts').textContent=accounts.size.toLocaleString();$('utilityRevision').textContent=plan.revision?`R${plan.revision}`:'—';$('utilitySourceFile').textContent=plan.sourceFile||'No upload yet';const body=$('utilityBody');if(!visible.length){body.innerHTML=`<tr><td colspan="18" class="empty-state">No ${CFG.name} rows match the current filter.</td></tr>`;return}const t=visible.reduce((o,x)=>{['budgetYtd','actualYtd','fyBudget','landing','annual'].forEach(k=>o[k]+=x[k]);MONTHS.forEach((_,i)=>o.months[monthKey(i)]+=x.months[monthKey(i)]);return o},{budgetYtd:0,actualYtd:0,fyBudget:0,landing:0,annual:0,months:Object.fromEntries(MONTHS.map((_,i)=>[monthKey(i),0]))});body.innerHTML=visible.map(x=>`<tr><td><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.cc)}</small></td><td>${money(x.budgetYtd)}</td><td>${money(x.actualYtd)}</td><td>${money(x.fyBudget)}</td><td>${money(x.landing)}</td>${MONTHS.map((_,i)=>`<td>${money(x.months[monthKey(i)])}</td>`).join('')}<td class="total27">${money(x.annual)}</td></tr>`).join('')+`<tr class="total-row"><td><b>TOTAL</b><small>${visible.length} Departments</small></td><td>${money(t.budgetYtd)}</td><td>${money(t.actualYtd)}</td><td>${money(t.fyBudget)}</td><td>${money(t.landing)}</td>${MONTHS.map((_,i)=>`<td>${money(t.months[monthKey(i)])}</td>`).join('')}<td>${money(t.annual)}</td></tr>`}

function sheetIndex(row,names){const normalized=row.map(x=>clean(x).toLowerCase());for(const name of names){const i=normalized.indexOf(name.toLowerCase());if(i>=0)return i}return-1}
function parseUpload(workbook){const matcher=maintenance?/^(maintenance budget|maintenance)$/i:/^(utilities budget|utilities)$/i,sheetName=workbook.SheetNames.find(n=>matcher.test(clean(n)));if(!sheetName)throw new Error(`${CFG.sheet} sheet is missing.`);const matrix=XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],{header:1,defval:'',raw:true}),hi=matrix.findIndex(r=>sheetIndex(r,['Target Fund Center','Fund Center'])>=0&&sheetIndex(r,['G/L Account','GL Account'])>=0&&sheetIndex(r,['Landing'])>=0&&sheetIndex(r,['Jan'])>=0&&sheetIndex(r,['Dec'])>=0);if(hi<0)throw new Error(`${CFG.sheet} headers are not valid. Download the latest template.`);const h=matrix[hi],ci=sheetIndex(h,['Target Fund Center','Fund Center']),gi=sheetIndex(h,['G/L Account','GL Account']),di=sheetIndex(h,['Details']),li=sheetIndex(h,['Landing']),mis=MONTHS.map(m=>sheetIndex(h,[m])),deptMap=byCc(),glMap=byGl(),rows=[];for(let i=hi+1;i<matrix.length;i++){const r=matrix[i]||[],cc=clean(r[ci]),gl=clean(r[gi]),landing=num(r[li]),months=Object.fromEntries(MONTHS.map((_,mi)=>[monthKey(mi),num(r[mis[mi]])])),fy=annual(months),active=Math.abs(landing)+Math.abs(fy)>.00001;if(!active)continue;if(!cc||!deptMap[cc])throw new Error(`${CFG.sheet} row ${i+1}: Target Fund Center ${cc||'(blank)'} is not approved.`);if(!gl||!gl.startsWith(CFG.prefix))throw new Error(`${CFG.sheet} row ${i+1}: G/L ${gl||'(blank)'} is not a ${CFG.prefix}xxxx ${CFG.name} account.`);if(centralAccounts.length&&!glMap[gl])throw new Error(`${CFG.sheet} row ${i+1}: G/L ${gl} is not in the Finance account master.`);rows.push({cc,departmentName:deptMap[cc].name,gl,accountName:glMap[gl]?.name||gl,details:di>=0?clean(r[di]):'',landing,newBudgetByMonth:months,annual:fy})}return rows}

function setWidths(ws,widths){ws['!cols']=widths.map(w=>({wch:w}))}
function downloadTemplate(){if(typeof XLSX==='undefined'){alert('Excel engine is still loading. Please try again.');return}if(!directory.length){alert('Department directory is not available yet.');return}if(!centralAccounts.length){alert(`No ${CFG.prefix}xxxx ${CFG.name} accounts were found in the Finance OPEX account master.`);return}const wb=XLSX.utils.book_new(),instructions=XLSX.utils.aoa_to_sheet([[`DAD BUDGET 2027 - ${CFG.name.toUpperCase()}`],['Owner','Engineering'],['Source Fund Center',ENGINEERING_CC],[],['HOW TO USE'],['1',`Every approved department and every ${CFG.prefix}xxxx account is included.`],['2','Budget YTD, Actual YTD and FY Budget 2026 are comparison values.'],['3','Fill Landing and Jan-Dec 2027 for the Target Fund Center shown on each row.'],['4','FY Budget 2027 is calculated automatically.'],['5',`Uploading replaces only the current central ${CFG.name} allocation and transfers each value to its Target Fund Center.`]]);setWidths(instructions,[22,100]);XLSX.utils.book_append_sheet(wb,instructions,'Instructions');const existing=new Map(plan.rows.map(r=>[`${r.cc}|${r.gl}`,r])),header=['Target Fund Center','Department','G/L Account','Account Name','Details','Budget YTD 2026','Actual YTD 2026','FY Budget 2026','Landing',...MONTHS,'FY Budget 2027'],data=[header];directory.forEach(d=>centralAccounts.forEach(a=>{const old=existing.get(`${d.cc}|${a.code}`)||{},ref=references.get(`${d.cc}|${a.code}`)||{},months=old.newBudgetByMonth||{};data.push([d.cc,d.name,a.code,a.name,clean(old.details),num(ref.budgetYtd),num(ref.actualYtd),num(ref.fyBudget),num(old.landing),...MONTHS.map((_,i)=>num(months[monthKey(i)])),''])}));const ws=XLSX.utils.aoa_to_sheet(data);for(let r=2;r<=data.length;r++)ws[`V${r}`]={t:'n',f:`SUM(J${r}:U${r})`};ws['!autofilter']={ref:`A1:V${Math.max(1,data.length)}`};setWidths(ws,[19,34,15,34,38,17,17,17,14,...Array(12).fill(12),17]);XLSX.utils.book_append_sheet(wb,ws,CFG.sheet);const ds=XLSX.utils.aoa_to_sheet([['Target Fund Center','Department'],...directory.map(d=>[d.cc,d.name])]);setWidths(ds,[20,45]);XLSX.utils.book_append_sheet(wb,ds,'Departments');const as=XLSX.utils.aoa_to_sheet([['G/L Account','Account Name'],...centralAccounts.map(a=>[a.code,a.name])]);setWidths(as,[18,50]);XLSX.utils.book_append_sheet(wb,as,`${CFG.name} Accounts`);XLSX.writeFile(wb,CFG.file)}

async function saveUpload(file){setStatus(`Validating ${CFG.name} workbook...`);const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),rows=parseUpload(wb),total=rows.reduce((s,r)=>s+num(r.annual),0),payload={fiscalYear:2027,sourceCc:ENGINEERING_CC,currency:'JOD',revision:num(plan.revision)+1,sourceFile:file.name,rows,total,departmentCount:new Set(rows.map(r=>r.cc)).size,accountCount:new Set(rows.map(r=>r.gl)).size,updatedBy:auth.currentUser.uid,updatedByEmail:clean(auth.currentUser.email).toLowerCase(),updatedAt:serverTimestamp(),clientUpdatedAt:new Date().toISOString()};await setDoc(doc(db,'system_status',CFG.planId),payload,{merge:false});plan={...payload,updatedAt:null};normalizePlan();cacheWrite(CFG.cache,{plan});try{localStorage.setItem(CFG.token,String(Date.now()));sessionStorage.removeItem('dadBudgetExecutiveCacheV3');sessionStorage.removeItem('dadBudgetOPEXSummaryCloudReadAt')}catch(_){}window.dispatchEvent(new CustomEvent(CFG.event,{detail:{revision:plan.revision,total}}));render();setStatus(`${file.name} · saved · R${plan.revision} · ${payload.departmentCount} departments`)}

async function boot(user){if(!user){location.href='login.html';return}try{profile=await loadProfile(user);if(!canManage(user,profile)){$('utilityContent').classList.add('hidden');$('utilityAccessDenied').classList.remove('hidden');return}await Promise.all([loadReference(),loadPlan()]);render();setStatus((plan.revision?`${CFG.name} loaded · R${plan.revision}`:`No ${CFG.name} upload yet · ready for Engineering input`)+referenceWarning);$('utilitySearch').addEventListener('input',render);$('utilityHideZero').onclick=()=>{hideZero=!hideZero;$('utilityHideZero').textContent=`Hide Zero: ${hideZero?'ON':'OFF'}`;$('utilityHideZero').classList.toggle('off',!hideZero);render()};$('utilityDownload').onclick=downloadTemplate;$('utilityUpload').onclick=()=>$('utilityUploadInput').click();$('utilityUploadInput').onchange=async()=>{const f=$('utilityUploadInput').files?.[0];if(!f)return;try{$('utilityUpload').disabled=true;await saveUpload(f)}catch(error){console.error(error);setStatus(`Upload failed: ${error.message||error}`,true);alert(`${CFG.name} upload rejected: ${error.message||error}`)}finally{$('utilityUpload').disabled=false;$('utilityUploadInput').value=''}};$('logoutBtn').onclick=async()=>{await signOut(auth);location.href='login.html'}}catch(error){console.error(error);setStatus(`${CFG.name} could not load: ${error.code||error.message||error}`,true);$('utilityBody').innerHTML=`<tr><td colspan="18" class="empty-state">${CFG.name} Budget could not load.</td></tr>`}}

configurePage();onAuthStateChanged(auth,boot);
