import {getApps,initializeApp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import {getAuth,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import {getFirestore,doc,getDoc,setDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyDAMLbm1ngqtzKjnDp6AMz8ucyhqNSnfBY',authDomain:'budget-8c575.firebaseapp.com',projectId:'budget-8c575',storageBucket:'budget-8c575.firebasestorage.app',messagingSenderId:'990142203884',appId:'1:990142203884:web:5c22dc2c14855528a022c9'};
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const MAIN_ADMIN_UID='PST3chwdZmaQGeG25t4ym9Vlixe2',ENGINEERING_CC='1000100301',PLAN_ID='utilities_budget_fy2027',PLAN_CACHE='dadBudgetUtilitiesPlanCacheV1',META_CACHE='dadBudgetUtilitiesMetaCacheV1',CACHE_MS=10*60*1000,META_CACHE_MS=30*60*1000;
const MONTHS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const $=id=>document.getElementById(id),clean=v=>String(v??'').trim(),num=v=>{if(typeof v==='number'&&Number.isFinite(v))return v;let s=clean(v).replace(/,/g,'');if(/^\(.*\)$/.test(s))s='-'+s.slice(1,-1);const n=Number(s);return Number.isFinite(n)?n:0},money=v=>num(v).toLocaleString(undefined,{maximumFractionDigits:0});
let profile=null,directory=[],utilityAccounts=[],plan={rows:[],revision:0,total:0,sourceFile:''},hideZero=true;

function cachedProfile(){try{return JSON.parse(localStorage.getItem('dadBudgetCurrentProfile')||'null')||null}catch(_){return null}}
function profileDepartments(p){return Array.isArray(p?.departments)?p.departments.map(clean):p?.department?[clean(p.department)]:[]}
function canManage(user,p){return !!user&&(user.uid===MAIN_ADMIN_UID||p?.isMainAdmin===true||p?.role==='admin'||profileDepartments(p).includes(ENGINEERING_CC))}
function setStatus(text,error=false){const el=$('utilityStatus');if(!el)return;el.textContent=text;el.classList.toggle('error',error);el.classList.toggle('ready',!error)}
function cacheRead(key,maxAge=CACHE_MS){try{const x=JSON.parse(sessionStorage.getItem(key)||'null');return x&&Date.now()-num(x.ts)<maxAge?x:null}catch(_){return null}}
function cacheWrite(key,data){try{sessionStorage.setItem(key,JSON.stringify({ts:Date.now(),...data}))}catch(_){}}
function clearPlanCache(){try{sessionStorage.removeItem(PLAN_CACHE)}catch(_){}}
function annual(months){return Object.entries(months||{}).reduce((s,[k,v])=>String(k).startsWith('2027-')?s+num(v):s,0)}
function monthKey(i){return `2027-${String(i+1).padStart(2,'0')}`}
function escapeHtml(v){return clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function byCc(){return Object.fromEntries(directory.map(x=>[clean(x.cc),x]))}
function byGl(){return Object.fromEntries(utilityAccounts.map(x=>[clean(x.code),x]))}

async function loadProfile(user){const local=cachedProfile();if(local&&(local.email?clean(local.email).toLowerCase()===clean(user.email).toLowerCase():true))return local;const snap=await getDoc(doc(db,'users',user.uid));return snap.exists()?snap.data()||{}:{} }
async function loadReference(){const cached=cacheRead(META_CACHE,META_CACHE_MS);if(cached?.directory&&cached?.accounts){directory=cached.directory;utilityAccounts=cached.accounts;return}const snap=await getDoc(doc(db,'opex_baseline_meta','current'));if(!snap.exists())throw new Error('Finance OPEX baseline is not published yet.');const data=snap.data()||{},rawDirectory=Array.isArray(data.departmentDirectory)?data.departmentDirectory:(data.departments||[]).map(cc=>({cc,name:cc})),master=Array.isArray(data.accountMaster)?data.accountMaster:Object.entries(data.accountMaster||{}).map(([code,x])=>({code:clean(x?.code||code),name:clean(x?.name||x?.code||code)}));directory=rawDirectory.map(x=>({cc:clean(x?.cc),name:clean(x?.name||x?.departmentName||x?.cc)})).filter(x=>x.cc&&x.cc!=='16').sort((a,b)=>a.name.localeCompare(b.name));utilityAccounts=master.map(x=>({code:clean(x?.code),name:clean(x?.name||x?.code)})).filter(x=>x.code.startsWith('608')).sort((a,b)=>a.code.localeCompare(b.code));cacheWrite(META_CACHE,{directory,accounts:utilityAccounts})}
async function loadPlan(force=false){const cached=!force&&cacheRead(PLAN_CACHE);if(cached?.plan){plan=cached.plan;normalizePlan();return}const snap=await getDoc(doc(db,'system_status',PLAN_ID));plan=snap.exists()?snap.data()||{}:{rows:[],revision:0,total:0,sourceFile:''};normalizePlan();cacheWrite(PLAN_CACHE,{plan})}
function normalizePlan(){plan={...plan,rows:Array.isArray(plan?.rows)?plan.rows:[],revision:num(plan?.revision),total:num(plan?.total),sourceFile:clean(plan?.sourceFile)};plan.rows=plan.rows.map(r=>({...r,cc:clean(r?.cc),departmentName:clean(r?.departmentName),gl:clean(r?.gl),accountName:clean(r?.accountName),details:clean(r?.details),landing:num(r?.landing),newBudgetByMonth:{...(r?.newBudgetByMonth||{})},annual:Number.isFinite(Number(r?.annual))?num(r.annual):annual(r?.newBudgetByMonth)})).filter(r=>r.cc&&r.gl.startsWith('608'))}

function aggregateRows(){const map={};plan.rows.forEach(r=>{const cc=clean(r.cc);if(!cc)return;const x=map[cc]||(map[cc]={cc,name:clean(r.departmentName)||byCc()[cc]?.name||cc,landing:0,months:Object.fromEntries(MONTHS.map((_,i)=>[monthKey(i),0])),annual:0});x.landing+=num(r.landing);MONTHS.forEach((_,i)=>x.months[monthKey(i)]+=num(r.newBudgetByMonth?.[monthKey(i)]));x.annual+=num(r.annual)});return Object.values(map)}
function render(){const rows=aggregateRows(),q=clean($('utilitySearch')?.value).toLowerCase(),visible=rows.filter(x=>(!hideZero||Math.abs(x.annual)+Math.abs(x.landing)>.005)&&(!q||`${x.cc} ${x.name}`.toLowerCase().includes(q))).sort((a,b)=>b.annual-a.annual||a.name.localeCompare(b.name));const total=plan.rows.reduce((s,r)=>s+num(r.annual),0),deps=new Set(plan.rows.filter(r=>Math.abs(num(r.annual))+Math.abs(num(r.landing))>.005).map(r=>r.cc)),accounts=new Set(plan.rows.filter(r=>Math.abs(num(r.annual))+Math.abs(num(r.landing))>.005).map(r=>r.gl));$('utilityTotal').textContent=money(total);$('utilityDepartments').textContent=deps.size.toLocaleString();$('utilityAccounts').textContent=accounts.size.toLocaleString();$('utilityRevision').textContent=plan.revision?`R${plan.revision}`:'—';$('utilitySourceFile').textContent=plan.sourceFile||'No upload yet';const body=$('utilityBody');if(!visible.length){body.innerHTML='<tr><td colspan="15" class="empty-state">No Utilities allocations match the current filter.</td></tr>';return}const t=visible.reduce((o,x)=>{o.landing+=x.landing;o.annual+=x.annual;MONTHS.forEach((_,i)=>o.months[monthKey(i)]+=x.months[monthKey(i)]);return o},{landing:0,annual:0,months:Object.fromEntries(MONTHS.map((_,i)=>[monthKey(i),0]))});body.innerHTML=visible.map(x=>`<tr><td><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.cc)}</small></td><td>${money(x.landing)}</td>${MONTHS.map((_,i)=>`<td>${money(x.months[monthKey(i)])}</td>`).join('')}<td class="total27">${money(x.annual)}</td></tr>`).join('')+`<tr class="total-row"><td><b>TOTAL</b><small>${visible.length} Departments</small></td><td>${money(t.landing)}</td>${MONTHS.map((_,i)=>`<td>${money(t.months[monthKey(i)])}</td>`).join('')}<td>${money(t.annual)}</td></tr>`}

function sheetIndex(row,names){const normalized=row.map(x=>clean(x).toLowerCase());for(const name of names){const i=normalized.indexOf(name.toLowerCase());if(i>=0)return i}return-1}
function parseUpload(workbook){const sheetName=workbook.SheetNames.find(n=>/^(utilities budget|utilities)$/i.test(clean(n)));if(!sheetName)throw new Error('Utilities Budget sheet is missing.');const matrix=XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],{header:1,defval:'',raw:true}),hi=matrix.findIndex(r=>sheetIndex(r,['Target Fund Center','Fund Center'])>=0&&sheetIndex(r,['G/L Account','GL Account'])>=0&&sheetIndex(r,['Jan'])>=0&&sheetIndex(r,['Dec'])>=0);if(hi<0)throw new Error('Utilities Budget headers are not valid. Download the latest template.');const h=matrix[hi],ci=sheetIndex(h,['Target Fund Center','Fund Center']),gi=sheetIndex(h,['G/L Account','GL Account']),di=sheetIndex(h,['Details']),li=sheetIndex(h,['Landing']),mis=MONTHS.map(m=>sheetIndex(h,[m])),deptMap=byCc(),glMap=byGl(),rows=[];for(let i=hi+1;i<matrix.length;i++){const r=matrix[i]||[],cc=clean(r[ci]),gl=clean(r[gi]),landing=li>=0?num(r[li]):0,months=Object.fromEntries(MONTHS.map((_,mi)=>[monthKey(mi),mis[mi]>=0?num(r[mis[mi]]):0])),fy=annual(months),active=Math.abs(landing)+Math.abs(fy)>.00001;if(!active)continue;if(!cc||!deptMap[cc])throw new Error(`Utilities Budget row ${i+1}: Target Fund Center ${cc||'(blank)'} is not in the approved department directory.`);if(!gl||!gl.startsWith('608'))throw new Error(`Utilities Budget row ${i+1}: G/L ${gl||'(blank)'} is not a Utilities 608xxxx account.`);if(utilityAccounts.length&&!glMap[gl])throw new Error(`Utilities Budget row ${i+1}: G/L ${gl} is not in the Finance Utilities account master.`);rows.push({cc,departmentName:deptMap[cc].name,gl,accountName:glMap[gl]?.name||gl,details:di>=0?clean(r[di]):'',landing,newBudgetByMonth:months,annual:fy})}return rows}

function setWidths(ws,widths){ws['!cols']=widths.map(w=>({wch:w}))}
function downloadTemplate(){if(typeof XLSX==='undefined'){alert('Excel engine is still loading. Please try again.');return}if(!directory.length){alert('Department directory is not available yet.');return}if(!utilityAccounts.length){alert('No 608xxxx Utilities accounts were found in the Finance OPEX account master.');return}const wb=XLSX.utils.book_new(),instructions=XLSX.utils.aoa_to_sheet([['DAD BUDGET 2027 - UTILITIES'],['Owner','Engineering'],['Source Fund Center',ENGINEERING_CC],[],['HOW TO USE'],['1','Enter Utilities allocation by Target Fund Center and 608xxxx G/L.'],['2','Fill Landing and Jan-Dec 2027 values as required.'],['3','FY Budget 2027 is calculated automatically.'],['4','Rows with zero Landing and zero FY Budget are ignored on upload.'],['5','Uploading replaces the current central Utilities allocation.']]);setWidths(instructions,[22,90]);XLSX.utils.book_append_sheet(wb,instructions,'Instructions');const existing=new Map(plan.rows.map(r=>[`${r.cc}|${r.gl}`,r])),header=['Target Fund Center','Department','G/L Account','Account Name','Details','Landing',...MONTHS,'FY Budget 2027'],data=[header];directory.forEach(d=>utilityAccounts.forEach(a=>{const old=existing.get(`${d.cc}|${a.code}`)||{},months=old.newBudgetByMonth||{};data.push([d.cc,d.name,a.code,a.name,clean(old.details),num(old.landing),...MONTHS.map((_,i)=>num(months[monthKey(i)])),''])}));const ws=XLSX.utils.aoa_to_sheet(data);for(let r=2;r<=data.length;r++)ws[`S${r}`]={t:'n',f:`SUM(G${r}:R${r})`};ws['!autofilter']={ref:`A1:S${Math.max(1,data.length)}`};setWidths(ws,[19,34,15,34,38,14,...Array(12).fill(12),17]);XLSX.utils.book_append_sheet(wb,ws,'Utilities Budget');const ds=XLSX.utils.aoa_to_sheet([['Target Fund Center','Department'],...directory.map(d=>[d.cc,d.name])]);setWidths(ds,[20,45]);XLSX.utils.book_append_sheet(wb,ds,'Departments');const as=XLSX.utils.aoa_to_sheet([['G/L Account','Account Name'],...utilityAccounts.map(a=>[a.code,a.name])]);setWidths(as,[18,50]);XLSX.utils.book_append_sheet(wb,as,'Utilities Accounts');XLSX.writeFile(wb,'Utilities_Budget_2027_Engineering.xlsx')}

async function saveUpload(file){setStatus('Validating Utilities workbook...');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),rows=parseUpload(wb),currentRevision=num(plan.revision),total=rows.reduce((s,r)=>s+num(r.annual),0),payload={fiscalYear:2027,sourceCc:ENGINEERING_CC,currency:'JOD',revision:currentRevision+1,sourceFile:file.name,rows,total,departmentCount:new Set(rows.map(r=>r.cc)).size,accountCount:new Set(rows.map(r=>r.gl)).size,updatedBy:auth.currentUser.uid,updatedByEmail:clean(auth.currentUser.email).toLowerCase(),updatedAt:serverTimestamp(),clientUpdatedAt:new Date().toISOString()};await setDoc(doc(db,'system_status',PLAN_ID),payload,{merge:false});plan={...payload,updatedAt:null};normalizePlan();cacheWrite(PLAN_CACHE,{plan});try{localStorage.setItem('dadBudgetUtilitiesRefreshToken',String(Date.now()));sessionStorage.removeItem('dadBudgetExecutiveCacheV3')}catch(_){}window.dispatchEvent(new CustomEvent('dad-utilities-budget-updated',{detail:{revision:plan.revision,total}}));render();setStatus(`${file.name} · saved · R${plan.revision} · ${plan.departmentCount||new Set(rows.map(r=>r.cc)).size} departments`)}

async function boot(user){if(!user){location.href='login.html';return}try{profile=await loadProfile(user);if(!canManage(user,profile)){$('utilityContent').classList.add('hidden');$('utilityAccessDenied').classList.remove('hidden');return}await Promise.all([loadReference(),loadPlan()]);render();setStatus(plan.revision?`Utilities loaded · R${plan.revision} · low-read mode`:'No Utilities upload yet · ready for Engineering input');$('utilitySearch').addEventListener('input',render);$('utilityHideZero').onclick=()=>{hideZero=!hideZero;$('utilityHideZero').textContent=`Hide Zero: ${hideZero?'ON':'OFF'}`;$('utilityHideZero').classList.toggle('off',!hideZero);render()};$('utilityDownload').onclick=downloadTemplate;$('utilityUpload').onclick=()=>$('utilityUploadInput').click();$('utilityUploadInput').onchange=async()=>{const f=$('utilityUploadInput').files?.[0];if(!f)return;try{$('utilityUpload').disabled=true;await saveUpload(f)}catch(error){console.error(error);setStatus(`Upload failed: ${error.message||error}`,true);alert('Utilities upload rejected: '+(error.message||error))}finally{$('utilityUpload').disabled=false;$('utilityUploadInput').value=''}};$('logoutBtn').onclick=async()=>{await signOut(auth);location.href='login.html'}}catch(error){console.error(error);setStatus(`Utilities could not load: ${error.code||error.message||error}`,true);$('utilityBody').innerHTML='<tr><td colspan="15" class="empty-state">Utilities Budget could not load.</td></tr>'}}

onAuthStateChanged(auth,boot);
